## using best practice
1. Preprocessing and datacleaning
2. Train Test Split
3. BOW,TFIDF, or Word2Vec
4. Train with ML Algos

In [2]:
!wget "https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/Kindle%20Reviews/all_kindle_review.csv"

import pandas as pd

df = pd.read_csv("all_kindle_review.csv")
df.head()

--2026-04-26 11:33:10--  https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/Kindle%20Reviews/all_kindle_review.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8593622 (8.2M) [text/plain]
Saving to: ‘all_kindle_review.csv’

all_kindle_review.c 100%[===================>]   8.20M  --.-KB/s    in 0.09s

2026-04-26 11:33:10 (92.7 MB/s) - ‘all_kindle_review.csv’ saved [8593622/8593622]

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [3]:
## extract only the columns that on which we have to perform the sentimental anaylsis
df=df[['reviewText','rating']]

In [4]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [5]:
df.shape

(12000, 2)

In [6]:
df.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [7]:
df['rating'].unique()

array([3, 5, 4, 2, 1])

In [8]:
df['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

#### 1. Preprocessing and Cleaning

In [9]:
## positive --> 1
## negative --> 0
df['rating'] = df['rating'].apply(lambda x: 0 if x < 2.5 else 1)

In [10]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [27]:
## 1. Lower all the cases
df['reviewText']=df['reviewText'].str.lower()

In [13]:
## 2. Removing special characters
import re
df['reviewText'] = df['reviewText'].apply(lambda x : re.sub('[^a-z AZ 0-9]+','',x))

In [22]:
## Removing all the stopwords
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))
df['reviewText'] = df['reviewText'].apply(lambda x : " ".join([y for y in x.split() if y not in stop_words]))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [23]:
## Remove URLs
df['reviewText'] = df['reviewText'].apply(lambda x: re.sub(r'(http|https|ftp|ssh)://\S+', '', str(x)))

In [24]:
## Remove html tags
from bs4 import BeautifulSoup
df['reviewText'] = df['reviewText'].apply(lambda x : BeautifulSoup(x,'lxml').get_text())

In [28]:
## Remove the additional spavces
df['reviewText'] = df['reviewText'].apply(lambda x: " ".join(x.split()))

In [29]:
df.head()

                                          reviewText  rating
0  ace ankin may short nothing mess man hauled sa...       1
1  reat short read want put read one sitting sex ...       1
2  start saying first four book expecting 34concl...       1
3  aggie angela ansbury carry pocketbook instead ...       1
4  expect type book library pleased find price right       1

In [30]:
## Applying wordnet lemmatizer
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [31]:
def lemmatize_words(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [32]:
df['reviewText'] = df['reviewText'].apply(lambda x: lemmatize_words(x))

In [33]:
df.head()

                                          reviewText  rating
0  ace ankin may short nothing mess man hauled sa...       1
1  reat short read want put read one sitting sex ...       1
2  start saying first four book expecting 34concl...       1
3  aggie angela ansbury carry pocketbook instead ...       1
4  expect type book library pleased find price right       1

In [34]:
X = df['reviewText']
y = df['rating']

#### 2. Train Test Split

In [41]:
## train test split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['reviewText'],df['rating'],test_size=0.20)

In [42]:
X_train

7532     ery rare find finishing book nfortunately deci...
11482    really wanted like well written short storyhow...
4850     elle aylor spent last year working eighty hour...
9705     woman abusive background find love lasting rel...
4810     tarting thriller book slows go seems lose orig...
                               ...
3780     ot sure polyamorus storyline enjoy world autho...
10217    review novel main theme presented detailed pro...
5036     ot hard figure mystery written wellenough stil...
431      a story orna ames went pleasantly surprised wa...
4630     love holy get competent proofreader book could...
Name: reviewText, Length: 9600, dtype: object

In [43]:
X_train.shape , y_train.shape , X_test.shape , y_test.shape

((9600,), (9600,), (2400,), (2400,))

#### 3. BOW,TFIDF, or Word2Vec

In [44]:
## Applying BOW
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer()

In [45]:
X_train_bow = bow.fit_transform(X_train).toarray()
X_test_bow = bow.transform(X_test).toarray()

In [46]:
## applying TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_train_tfidf = tfidf.fit_transform(X_train).toarray()
X_test_tfidf = tfidf.transform(X_test).toarray()

#### we will compare both TFIDF and BOW

In [47]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

#### 4. Train with ML Algos --> Gaussian Naive Bias

In [48]:
## apply ml algo
from sklearn.naive_bayes import GaussianNB
nb_model_bow = GaussianNB().fit(X_train_bow,y_train)
nb_mode_tfidf = GaussianNB().fit(X_train_tfidf,y_train)

In [49]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [50]:
y_pred_tfidf = nb_mode_tfidf.predict(X_test_tfidf)

In [51]:
print("BOW accuracy: ",accuracy_score(y_test,y_pred_bow))

BOW accuracy:  0.595

In [52]:
confusion_matrix(y_test,y_pred_bow)

array([[493, 294],
       [678, 935]])

In [53]:
print("TFIDF accuracy: ",accuracy_score(y_test,y_pred_tfidf))

TFIDF accuracy:  0.5983333333333334

In [54]:
confusion_matrix(y_test,y_pred_tfidf)

array([[488, 299],
       [665, 948]])

## As the accuracy is not good so we will try it with Word2Vec
- Word2Vec is better of this type of huge dataset
- using the Gensim library

In [56]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 20.4 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [57]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [59]:
X_train

7532     ery rare find finishing book nfortunately deci...
11482    really wanted like well written short storyhow...
4850     elle aylor spent last year working eighty hour...
9705     woman abusive background find love lasting rel...
4810     tarting thriller book slows go seems lose orig...
                               ...
3780     ot sure polyamorus storyline enjoy world autho...
10217    review novel main theme presented detailed pro...
5036     ot hard figure mystery written wellenough stil...
431      a story orna ames went pleasantly surprised wa...
4630     love holy get competent proofreader book could...
Name: reviewText, Length: 9600, dtype: object

In [64]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [65]:
words = []
for sent in X_train:
  sent_token = sent_tokenize(sent)
  for word in sent_token:
    words.append(simple_preprocess(word))

In [66]:
words

[['ery',
  'rare',
  'find',
  'finishing',
  'book',
  'nfortunately',
  'decided',
  'one',
  'hold',
  'attention',
  'however',
  'best',
  'read',
  'searching',
  'amazon',
  'found',
  'book',
  'rather',
  'read',
  'put',
  'one',
  'decided',
  'hurry',
  'pick',
  'back',
  'finish',
  'last',
  'anytime',
  'soonhere',
  'allot',
  'page',
  'filled',
  'justuseless',
  'story',
  'telling',
  'little',
  'story',
  'mesh',
  'together',
  'ike',
  'different',
  'idea',
  'used',
  'real',
  'thought',
  'go',
  'together',
  'ou',
  'try',
  'put',
  'chemistry',
  'romance',
  'book',
  'reader',
  'actually',
  'feel',
  'itwell',
  'ori',
  'missed'],
 ['really',
  'wanted',
  'like',
  'well',
  'written',
  'short',
  'storyhoweverit',
  'sweet',
  'unbelievable',
  'go',
  'fantasy'],
 ['elle',
  'aylor',
  'spent',
  'last',
  'year',
  'working',
  'eighty',
  'hour',
  'week',
  'without',
  'single',
  'day',
  'hristmas',
  'time',
  'od',
  'going',
  'visit',
  'family',
  'week',
  'want',
  'corner',
  'office',
  'law',
  'firm',
  'work',
  'also',
  'want',
  'spend',
  'time',
  'family',
  'hen',
  'afe',
  'brother',
  'best',
  'friend',
  'object',
  'late',
  'night',
  'fantasy',
  'since',
  'high',
  'school',
  'kiss',
  'mistletoe',
  'hanging',
  'hallway',
  'elle',
  'realizes',
  'used',
  'think',
  'important',
  'might',
  'longerafe',
  'ettencourt',
  'love',
  'elle',
  'since',
  'graduated',
  'law',
  'school',
  'inding',
  'love',
  'best',
  'friend',
  'baby',
  'sister',
  'tough',
  'enough',
  'afe',
  'compete',
  'list',
  'goal',
  'elle',
  'obsessively',
  'make',
  'need',
  'convince',
  'life',
  'would',
  'way',
  'better',
  'list',
  'could',
  'ever',
  'makeo',
  'ist',
  'new',
  'fully',
  'anticipated',
  'experience',
  'auren',
  'ane',
  'one',
  'favorite',
  'author',
  'think',
  'first',
  'totally',
  'contemporary',
  'romance',
  'read',
  'written',
  'ist',
  'made',
  'giggle',
  'simply',
  'elle',
  'amous',
  'family',
  'list',
  'empathized',
  'need',
  'organized',
  'loved',
  'quirkiness',
  'endeared',
  'afe',
  'simply',
  'loved',
  'afe',
  'loved',
  'elle',
  'patience',
  'even',
  'dying',
  'come',
  'grip',
  'relationship',
  'appealing',
  'simply',
  'desired',
  'owneaders',
  'used',
  'reading',
  'auren',
  'anes',
  'outstanding',
  'fantasy',
  'shape',
  'shifter',
  'novel',
  'need',
  'give',
  'ist',
  'try',
  'wholeheartedly',
  'adored',
  'italiareviewed',
  'oyfully',
  'eviewed'],
 ['woman',
  'abusive',
  'background',
  'find',
  'love',
  'lasting',
  'relationship',
  'apparently',
  'find',
  'love',
  'need',
  'menage',
  'trois',
  'apparently',
  'hris',
  'able',
  'overcome',
  'trauma',
  'raised',
  'alcoholic',
  'abusive',
  'father',
  'mother',
  'completely',
  'submissive',
  'hrow',
  'brother',
  'grown',
  'like',
  'father',
  'poor',
  'girl',
  'lot',
  'overcome',
  'help',
  'lover',
  'short',
  'read',
  'done',
  'one',
  'evening',
  'hile',
  'standing',
  'entertaining',
  'hris',
  'given',
  'lot',
  'credit',
  'strength',
  'overcoming',
  'horrible',
  'background'],
 ['tarting',
  'thriller',
  'book',
  'slows',
  'go',
  'seems',
  'lose',
  'original',
  'voice',
  'mark',
  'convinced',
  'could',
  'satisfying',
  'ending',
  'stayed',
  'right',
  'unsatisfying',
  'endingt',
  'really',
  'disappointed',
  'book',
  'started',
  'strong',
  'premise',
  'seems',
  'incredibly',
  'solid',
  'hat',
  'would',
  'happen',
  'irgin',
  'arys',
  'body',
  'discovered',
  'arrie',
  'ather',
  'itzpatrick',
  'esev',
  'milio',
  'hese',
  'incredibly',
  'well',
  'written',
  'character',
  'author',
  'begin',
  'story',
  'building',
  'interest',
  'enough',
  'information',
  'motivation',
  'want',
  'know',
  'ut',
  'past',
  'half',
  'way',
  'point',
  'thing',
  'begin',
  'come',
  'apart',
  'ur',
  'interesting',
  'character',
  'seems',
  'go',
  'one',
  'dimensional',
  'arrie',
  'longer',
  'complex',
  'woman',
  'less',
  'capable',
  'focusing',
  'irgin',
  'milio',
  'turn',
  'standard',
  'hit',
  'man',
  'caricature',
  'itzpatrick',
  'like',
  'schoolboy',
  'girlfriend',
  'stop',
  'paying',
  'attention',
  'himy',
  'end',
  'book',
  'main',
  'character',
  'meeting',
  'underdeveloped',
  'bad',
  'guy',
  'right',
  'wing',
  'politician',
  'irgin',
  'apparently',
  'hurricane',
  'manifestation',
  'god',
  'god',
  'hate',
  'religion',
  'know',
  'even',
  'one',
  'disciple',
  'founded',
  'enviromentalist',
  'toohe',
  'afterward',
  'clear',
  'question',
  'story',
  'began',
  'probably',
  'unraveled',
  'course',
  'make',
  'book',
  'good',
  'read'],
 ['oorly',
  'written',
  'like',
  'crime',
  'fiction',
  'used',
  'violence',
  'awful',
  'overboard',
  'quickly',
  'bored',
  'even',
  'get',
  'third',
  'chapter'],
 ['irst',
  'description',
  'given',
  'book',
  'go',
  'great',
  'review',
  'hope',
  'best',
  'allow',
  'give',
  'background',
  'heroine',
  'married',
  'abusive',
  'husband',
  'lot',
  'money',
  'run',
  'town',
  'due',
  'control',
  'logging',
  'business',
  'one',
  'great',
  'kid',
  'one',
  'delinquent',
  'beaten',
  'hubby',
  'show',
  'annoyance',
  'concern',
  'kid',
  'obviously',
  'dealing',
  'dysfunctioanl',
  'family',
  'way',
  'need',
  'help',
  'take',
  'crap',
  'husband',
  'kid',
  'pretty',
  'much',
  'everyone',
  'hero',
  'work',
  'environmental',
  'agency',
  'see',
  'man',
  'wife',
  'smile',
  'go',
  'infatuation',
  'love',
  'terrified',
  'husband',
  'nerve',
  'leave',
  'getting',
  'nerve',
  'affair',
  'front',
  'whole',
  'gossiping',
  'town',
  'tramp',
  'friend',
  'take',
  'dinner',
  'seen',
  'everyone',
  'eatting',
  'hero',
  'coworker',
  'onestly',
  'one',
  'infidelity',
  'even',
  'cheating',
  'abusivecheating',
  'husband',
  'get',
  'controlling',
  'powerful',
  'guy',
  'afraid',
  'leave',
  'think',
  'cheating',
  'compared',
  'ridge',
  'adison',
  'ounty',
  'anywhere',
  'near',
  'good',
  'may',
  'infidelity',
  'intensity',
  'written',
  'well',
  'finish',
  'hope',
  'better',
  'luck',
  'chose',
  'read'],
 ['seem',
  'get',
  'ept',
  'hoping',
  'would',
  'get',
  'better',
  'finally',
  'gave',
  'idnt',
  'like',
  'character',
  'poorly',
  'written'],
 ['enjoy',
  'book',
  'ritten',
  'first',
  'person',
  'first',
  'doctor',
  'reach',
  'resident',
  'oignant',
  'personal',
  'excellently',
  'framed',
  'paced',
  'ood',
  'read'],
 ['eviewed',
  'posted',
  'nder',
  'ook',
  'log',
  'second',
  'book',
  'ragon',
  'night',
  'series',
  'hile',
  'believe',
  'book',
  'strong',
  'standalone',
  'adora',
  'ared',
  'introduced',
  'romance',
  'really',
  'stem',
  'book',
  'take',
  'different',
  'approach',
  'first',
  'book',
  'thought',
  'arc',
  'really',
  'changed',
  'tone',
  'series',
  'one',
  'hings',
  'far',
  'bigger',
  'book',
  'war',
  'approaching',
  'dark',
  'time',
  'ared',
  'life',
  'constant',
  'darkness',
  'since',
  'wife',
  'child',
  'died',
  'grief',
  'still',
  'lingers',
  'within',
  'feel',
  'unworthy',
  'adoras',
  'love',
  'even',
  'though',
  'willing',
  'give',
  'freely',
  'deems',
  'undeserving',
  'think',
  'reader',
  'touched',
  'areds',
  'gentle',
  'heart',
  'adora',
  'gentle',
  'cox',
  'ared',
  'shell',
  'slowly',
  'learns',
  'way',
  'romance',
  'continues',
  'bloom',
  'arc',
  'really',
  'cement',
  'fact',
  'meant',
  'together',
  'third',
  'member',
  'introduced',
  'ord',
  'arian',
  'come',
  'warn',
  'death',
  'destruction',
  'come',
  'way',
  'though',
  'seen',
  'traitor',
  'ared',
  'welcome',
  'old',
  'friend',
  'arian',
  'take',
  'immediate',
  'interest',
  'adora',
  'spark',
  'fly',
  'two',
  'owever',
  'arian',
  'member',
  'royal',
  'line',
  'black',
  'dragon',
  'adora',
  'aware',
  'cannot',
  'something',
  'permanent',
  'arian',
  'even',
  'though',
  'desperately',
  'want',
  'toarc',
  'experiment',
  'mating',
  'rule',
  'ritual',
  'introduced',
  'first',
  'book',
  'liked',
  'seeing',
  'happy',
  'ending',
  'end',
  'felt',
  'solution',
  'conflict',
  'seemed',
  'happen',
  'conveniently',
  'also',
  'felt',
  'romance',
  'slightly',
  'impeded',
  'areds',
  'hesitancy',
  'seemed',
  'fasttrack',
  'quickly',
  'made',
  'decision',
  'adora',
  'make',
  'time',
  'lost',
  'evertheless',
  'enraptured',
  'arc',
  'world',
  'ringing',
  'together',
  'dragon',
  'war',
  'love',
  'arc',
  'readily',
  'able',
  'transport',
  'reader',
  'another',
  'time',
  'giving',
  'escape',
  'sure',
  'rememberhe',
  'se',
  'scene',
  'explicit',
  'welldone',
  'arc',
  'explores',
  'light',
  'bondage',
  'meacutena',
  'ge',
  'well',
  'always',
  'looking',
  'forward',
  'seeing',
  'bring',
  'three',
  'different',
  'people',
  'together',
  'purpose',
  'love',
  'seems',
  'stellar',
  'job',
  'timea',
  'provided',
  'publisher'],
 ['started',
  'series',
  'backwards',
  'happened',
  'across',
  'recent',
  'book',
  'first',
  'etting',
  'otter',
  'read',
  'next',
  'last',
  'one',
  'eeling',
  'ot',
  'author',
  'improved',
  'added',
  'detail',
  'story',
  'since',
  'first',
  'book',
  'ut',
  'niform',
  'series',
  'ont',
  'get',
  'wrong',
  'enjoy',
  'book',
  'immensely',
  'wish',
  'longer'],
 ['enjoy',
  'book',
  'realize',
  'everyone',
  'opinion',
  'one',
  'mine',
  'tried',
  'tried',
  'hard',
  'get',
  'story',
  'man',
  'impossible',
  'ignore',
  'stilted',
  'dialogue',
  'seemed',
  'almost',
  'moronic',
  'logic',
  'character',
  'felt',
  'like',
  'hero',
  'heroine',
  'almost',
  'stereotypicala',
  'woman',
  'man',
  'world',
  'trying',
  'strong',
  'fighting',
  'nature',
  'heroa',
  'strong',
  'alphamale',
  'seems',
  'know',
  'everyone',
  'thinking'],
 ['really',
  'liked',
  'story',
  'overall',
  'enjoyed',
  'however',
  'adding',
  'say',
  'chapter',
  'cover',
  'day',
  'spent',
  'contest',
  'would',
  'helped',
  'bring',
  'character',
  'life',
  'fleshed',
  'story',
  'could',
  'seen',
  'went',
  'know',
  'would',
  'enjoyed',
  'interesting',
  'character',
  'gotten',
  'deeper',
  'story',
  'erhaps',
  'little',
  'argo',
  'playing',
  'hard',
  'get',
  'drawing',
  'romance',
  'seductionor',
  'longer',
  'story',
  'would',
  'definitely',
  'add',
  'another',
  'starhe',
  'author',
  'definitely',
  'talented'],
 ['excellent',
  'read',
  'caught',
  'first',
  'page',
  'oved',
  'bother',
  'write',
  'etain',
  'number',
  'word',
  'order',
  'submit',
  'review'],
 ['ice',
  'idea',
  'real',
  'people',
  'nice',
  'development',
  'short',
  'piece',
  'nice',
  'writing',
  'sex',
  'butollow',
  'little',
  'weak',
  'poiler',
  'alert',
  'dad',
  'want',
  'bracelet',
  'badlya',
  'hero',
  'need',
  'involved',
  'climax',
  'ot',
  'dither',
  'ot',
  'make',
  'phone',
  'call',
  'save',
  'girl',
  'bad',
  'guy',
  'holding',
  'gun',
  'ithering',
  'attractive',
  'give',
  'gun',
  'going',
  'use',
  'ou',
  'bring',
  'follow',
  'bring',
  'upo',
  'follow',
  'writer',
  'hope',
  'little',
  'improvement',
  'follow'],
 ['finished',
  'book',
  'quite',
  'frankly',
  'trouble',
  'putting',
  'part',
  'trouble',
  'picking',
  'others',
  'ome',
  'place',
  'story',
  'got',
  'bogged',
  'part',
  'enjoyed',
  'book',
  'character',
  'well',
  'defined',
  'interesting',
  'story',
  'seemed',
  'lack',
  'point',
  'goal',
  'get',
  'first',
  'book',
  'nce',
  'established',
  'story',
  'came',
  'together',
  'well',
  'found',
  'typo',
  'distracting',
  'several',
  'time',
  'making',
  'stop',
  'reread',
  'sentence',
  'time',
  'try',
  'figure',
  'supposed',
  'say',
  'probably',
  'would',
  'rated',
  'star',
  'except',
  'many',
  'error',
  'inconsistancies',
  'find',
  'indle',
  'flip',
  'back',
  'compare',
  'part',
  'book',
  'much',
  'sometimes',
  'get',
  'little',
  'confused',
  'thing',
  'quite',
  'fit',
  'one',
  'chapter',
  'another',
  'ie',
  'thing',
  'someone',
  'else',
  'noted',
  'regarding',
  'nameall',
  'said',
  'disappointed',
  'next',
  'book',
  'yet',
  'available',
  'hat',
  'actually',
  'say',
  'review',
  'anything',
  'else',
  'want'],
 ['enjoyed',
  'story',
  'thought',
  'interesting',
  'enough',
  'finish',
  'one',
  'sitting',
  'female',
  'hard',
  'male',
  'sensitive',
  'enough',
  'take',
  'care',
  'liked',
  'action',
  'fight',
  'scene',
  'able',
  'follow',
  'ow',
  'think',
  'would',
  'lost',
  'control',
  'razorsharp',
  'rock',
  'simple',
  'lust',
  'one',
  'anothergetting',
  'would',
  'last',
  'thing',
  'mind'],
 ['good',
  'put',
  'character',
  'passionate',
  'story',
  'cant',
  'wait',
  'read',
  'next',
  'story',
  'tory',
  'full',
  'interesting',
  'character',
  'lot',
  'sex',
  'highly',
  'recommend',
  'book'],
 ['like',
  'chapter',
  'even',
  'novella',
  'plot',
  'sex',
  'animal',
  'get',
  'must',
  'preview',
  'though',
  'remember',
  'seeing',
  'description',
  'buy',
  'book',
  'either',
  'preview',
  'high',
  'schooldrama',
  'book'],
 ['didnt',
  'like',
  'book',
  'much',
  'sexual',
  'content',
  'mostly',
  'threesome',
  'didnt',
  'find',
  'romantic',
  'author',
  'book',
  'way',
  'better'],
 ['fault',
  'read',
  'review',
  'knew',
  'dicey',
  'liked',
  'concept',
  'gay',
  'doctor',
  'straight',
  'cowboy',
  'baby',
  'surely',
  'good',
  'ingredient',
  'make',
  'something',
  'delicious',
  'ell',
  'sadly',
  'flat',
  'boring',
  'character',
  'development',
  'time',
  'line',
  'choppy',
  'like',
  'blog',
  'entry',
  'strung',
  'together',
  'coherent',
  'story',
  'time',
  'line',
  'character',
  'come',
  'disappear',
  'zelda',
  'teven',
  'really',
  'badly',
  'written',
  'even',
  'poor',
  'investment',
  'ave',
  'time',
  'money',
  'find',
  'something',
  'better'],
 ['isturbing',
  'felt',
  'nook',
  'ery',
  'graphic',
  'extremely',
  'demeaning',
  'woman',
  'get',
  'submission',
  'stuff',
  'way',
  'top',
  'stopped',
  'reading',
  'several',
  'time',
  'going',
  'finish',
  'book',
  'felt',
  'obligated',
  'since',
  'paid',
  'ertainly',
  'different',
  'read',
  'author',
  'previously'],
 ['reprint',
  'prior',
  'book',
  'xiles',
  'alor',
  'cool',
  'good',
  'book',
  'want',
  'two',
  'copy',
  'thing'],
 ['ntricately',
  'woven',
  'past',
  'present',
  'story',
  'allie',
  'cuire',
  'ischief',
  'abducted',
  'gypsy',
  'sold',
  'udgement',
  'along',
  'captive',
  'sadistically',
  'beaten',
  'trained',
  'submission',
  'sold',
  'around',
  'globe',
  'like',
  'ischief',
  'kept',
  'become',
  'ersonal',
  'aster',
  'udgement',
  'udgement',
  'primarily',
  'story',
  'ane',
  'ischief',
  'span',
  'nearly',
  'ten',
  'year',
  'uthless',
  'begin',
  'describe',
  'treatment',
  'slave',
  'ery',
  'well',
  'written',
  'hard',
  'put'],
 ['ust',
  'bought',
  'found',
  'list',
  'book',
  'contain',
  'specific',
  'plot',
  'twist',
  'usually',
  'enjoy',
  'usually',
  'like',
  'author',
  'work',
  'even',
  'finish',
  'though',
  'made',
  'angry',
  'get',
  'tendency',
  'author',
  'fall',
  'back',
  'youre',
  'mate',
  'instantly',
  'lovelust',
  'plotline',
  'hated',
  'way',
  'handled',
  'bookeil',
  'yan',
  'spent',
  'many',
  'year',
  'sex',
  'slave',
  'physical',
  'mental',
  'emotional',
  'trauma',
  'entail',
  'seen',
  'author',
  'handle',
  'type',
  'situation',
  'realistic',
  'sensitive',
  'manner',
  'barely',
  'even',
  'addressed',
  'book',
  'main',
  'character',
  'begin',
  'physical',
  'relationship',
  'nstead',
  'author',
  'would',
  'believe',
  'disappeared',
  'met',
  'abe',
  'mating',
  'bond',
  'author',
  'willing',
  'even',
  'eager',
  'jump',
  'bed',
  'abe',
  'within',
  'hour',
  'meeting',
  'even',
  'though',
  'large',
  'intimidating',
  'man',
  'similar',
  'men',
  'held',
  'men',
  'apparently',
  'terrified',
  'consider',
  'cop',
  'using',
  'instant',
  'love',
  'instant',
  'trust',
  'mating',
  'bond',
  'author',
  'lazy',
  'incapable',
  'actually',
  'addressing',
  'deeper',
  'issue',
  'involved',
  'aftermath',
  'abuse',
  'realize',
  'fiction',
  'fantasy',
  'fiction',
  'really',
  'cant',
  'write',
  'kind',
  'issue',
  'anything',
  'even',
  'remotely',
  'resembling',
  'realistic',
  'manner',
  'write'],
 ['great',
  'story',
  'young',
  'man',
  'despite',
  'awful',
  'lifestyle',
  'find',
  'od',
  'help',
  'favor',
  'lot',
  'first',
  'person',
  'narrative',
  'book',
  'bother',
  'might',
  'like',
  'much',
  'story',
  'told',
  'eye',
  'fourteen',
  'year',
  'old',
  'boy',
  'first',
  'series',
  'opinion',
  'read',
  'book',
  'order',
  'chance',
  'eta',
  'read',
  'third',
  'book',
  'part',
  'pretty',
  'confusing',
  'without',
  'reading',
  'one',
  'first',
  'author',
  'illiam',
  'oodall',
  'gracious',
  'enough',
  'give',
  'book',
  'one',
  'two',
  'glad',
  'refreshing',
  'fantasy',
  'written',
  'hristian',
  'view',
  'give',
  'star',
  'good',
  'read',
  'age',
  'igh'],
 ['star',
  'anney',
  'captivating',
  'somewhat',
  'sad',
  'yet',
  'sweet',
  'ugly',
  'duckling',
  'theme',
  'ouisa',
  'belief',
  'ugly',
  'unattractive',
  'actually',
  'ugly',
  'hears',
  'snicker',
  'enters',
  'room',
  'horrible',
  'insult',
  'launched',
  'back',
  'pas',
  'know',
  'man',
  'truly',
  'want',
  'anything',
  'extensive',
  'dowry',
  'hen',
  'encounter',
  'dark',
  'stranger',
  'life',
  'cave',
  'keep',
  'shadow',
  'whose',
  'soothing',
  'voice',
  'demeanor',
  'intrigue',
  'attracts',
  'soon',
  'learns',
  'person',
  'reflected',
  'mirror',
  'others',
  'eye',
  'ouglas',
  'fear',
  'trying',
  'live',
  'world',
  'alongside',
  'different',
  'endangers',
  'cross',
  'path',
  'oon',
  'learns',
  'whereas',
  'normal',
  'concept',
  'human',
  'strive',
  'obtain',
  'one',
  'truly',
  'normal',
  'may',
  'accepted',
  'difference',
  'easily',
  'expectshis',
  'dark',
  'sweet',
  'novella',
  'love',
  'overcoming',
  'diversity',
  'beauty',
  'eye',
  'beholder',
  'keep',
  'enthralled',
  'beginning',
  'moment',
  'ouisa',
  'discovers',
  'cave',
  'home',
  'ouglas',
  'reveal',
  'dark',
  'secret',
  'lovely',
  'dance',
  'moonlight',
  'eventual',
  'highly',
  'recommend',
  'reading',
  'anney',
  'number',
  'reason',
  'listed',
  'mostly',
  'good',
  'fact',
  'wish',
  'longeropy',
  'gifted',
  'part',
  'subscribing',
  'author',
  'newsletter',
  'review',
  'honest',
  'unscripted',
  'requested',
  'author'],
 ['bundle',
  'brings',
  'brother',
  'together',
  'sexy',
  'hell',
  'box',
  'set',
  'uckhorn',
  'men',
  'damn',
  'sexy',
  'sweet',
  'yes',
  'even',
  'organ',
  'fall',
  'minuteas',
  'always',
  'ori',
  'oster',
  'great',
  'series',
  'read',
  'one',
  'time',
  'awyer',
  'favorite',
  'sexy',
  'hell',
  'doctor',
  'organ',
  'although',
  'tough',
  'nail',
  'think',
  'lovable',
  'ove',
  'closeness',
  'family',
  'brother',
  'course',
  'awyers',
  'son',
  'asey',
  'ho',
  'love',
  'house',
  'full',
  'men',
  'haha',
  'oth',
  'awyer',
  'organ',
  'love',
  'single',
  'know',
  'hometown',
  'reputation',
  'aloud',
  'cut',
  'loose',
  'oney',
  'break',
  'awyers',
  'fence',
  'awyers',
  'defense',
  'cant',
  'help',
  'fall',
  'beautiful',
  'strong',
  'woman',
  'hen',
  'come',
  'isty',
  'oneys',
  'sister',
  'come',
  'visit',
  'organ',
  'cant',
  'help',
  'strong',
  'arm',
  'loving',
  'awyer',
  'sweet',
  'sexy',
  'hell',
  'romantic',
  'smitten',

In [68]:
import gensim

In [69]:
## training the word2vec model from scratch
model = gensim.models.Word2Vec(words)

In [70]:
## to get all the vocabulary
model.wv.index_to_key

['book',
 'story',
 'read',
 'character',
 'one',
 'like',
 'good',
 'would',
 'really',
 'author',
 'get',
 'time',
 'love',
 'series',
 'reading',
 'much',
 'first',
 'well',
 'know',
 'short',
 'way',
 'even',
 'make',
 'could',
 'sex',
 'little',
 'want',
 'thing',
 'great',
 'two',
 'think',
 'find',
 'plot',
 'also',
 'end',
 'romance',
 'life',
 'go',
 'enjoyed',
 'scene',
 'see',
 'never',
 'take',
 'say',
 'ut',
 'bit',
 'woman',
 'written',
 'work',
 'found',
 'lot',
 'many',
 'give',
 'going',
 'thought',
 'novel',
 'year',
 'writing',
 'better',
 'liked',
 'feel',
 'another',
 'interesting',
 'hat',
 'and',
 'come',
 'got',
 'back',
 'enough',
 'made',
 'people',
 'man',
 'friend',
 'reader',
 'something',
 'review',
 'page',
 'part',
 'though',
 'need',
 'bad',
 'still',
 'indle',
 'loved',
 'free',
 'cant',
 'relationship',
 'world',
 'together',
 'star',
 'hot',
 'felt',
 'next',
 'keep',
 'enjoy',
 'recommend',
 'start',
 'hen',
 'put',
 'best',
 'main',
 'new',
 'word',
 'ot',
 'guy',
 'fun',
 'hard',
 'day',
 'line',
 'right',
 'looking',
 'ending',
 'long',
 'real',
 'without',
 'point',
 'hey',
 'different',
 'sure',
 'wanted',
 'anything',
 'ever',
 'family',
 'always',
 'since',
 'men',
 'action',
 'actually',
 'help',
 'look',
 'fact',
 'quite',
 'around',
 'worth',
 'heroine',
 'pretty',
 'feeling',
 'old',
 'place',
 'problem',
 'every',
 'left',
 'tell',
 'hero',
 'might',
 'whole',
 'nothing',
 'idea',
 'seemed',
 'away',
 'definitely',
 'try',
 'three',
 'kind',
 'almost',
 'started',
 'let',
 'sexy',
 'getting',
 'couple',
 'someone',
 'second',
 'may',
 'chapter',
 'far',
 'brother',
 'turn',
 'issue',
 'kept',
 'seems',
 'done',
 'novella',
 'past',
 'last',
 'mystery',
 'set',
 'finish',
 'writer',
 'girl',
 'reason',
 'nice',
 'said',
 'tale',
 'ou',
 'trying',
 'yet',
 'beginning',
 'job',
 'night',
 'vampire',
 'strong',
 'description',
 'quick',
 'others',
 'mind',
 'everything',
 'believe',
 'meet',
 'wish',
 'hope',
 'full',
 'able',
 'development',
 'least',
 'human',
 'must',
 'anyone',
 'care',
 'mean',
 'detail',
 'understand',
 'fan',
 'erotic',
 'owever',
 'fantasy',
 'ow',
 'although',
 'father',
 'mate',
 'happy',
 'young',
 'sense',
 'easy',
 'went',
 'sweet',
 'seem',
 'show',
 'money',
 'thats',
 'used',
 'buy',
 'forward',
 'ook',
 'storyline',
 'home',
 'took',
 'write',
 'style',
 'disappointed',
 'child',
 'case',
 'person',
 'rest',
 'along',
 'probably',
 'gave',
 'ill',
 'less',
 'interest',
 'especially',
 'sexual',
 'wait',
 'female',
 'use',
 'favorite',
 'big',
 'after',
 'fast',
 'else',
 'change',
 'told',
 'type',
 'came',
 'true',
 'rather',
 'ell',
 'longer',
 'either',
 'several',
 'twist',
 'given',
 'male',
 'heart',
 'knew',
 'price',
 'completely',
 'error',
 'lack',
 'future',
 'lead',
 'wrong',
 'lost',
 'light',
 'developed',
 'wonderful',
 'er',
 'perfect',
 'high',
 'husband',
 'alpha',
 'fall',
 'cover',
 'happened',
 'name',
 'glad',
 'happens',
 'making',
 'stop',
 'interested',
 'ust',
 'course',
 'ne',
 'finally',
 'maybe',
 'age',
 'instead',
 'wife',
 'however',
 'bought',
 'side',
 'premise',
 'all',
 'enjoyable',
 'order',
 'later',
 'attention',
 'needed',
 'already',
 'quickly',
 'situation',
 'hile',
 'entire',
 'half',
 'happen',
 'become',
 'ood',
 'kindle',
 'sister',
 'truly',
 'waste',
 'finished',
 'believable',
 'boring',
 'thinking',
 'fiction',
 'school',
 'ended',
 'follow',
 'live',
 'dialogue',
 'moment',
 'amazon',
 'guess',
 'eye',
 'ery',
 'funny',
 'chance',
 'town',
 'werewolf',
 'reat',
 'steamy',
 'entertaining',
 'move',
 'leave',
 'everyone',
 'experience',
 'at',
 'language',
 'title',
 'call',
 'mother',
 'stand',
 'ith',
 'alone',
 'head',
 'romantic',
 'add',
 'begin',
 'reviewer',
 'expect',
 'totally',
 'version',
 'genre',
 'sort',
 'ven',
 'month',
 'hand',
 'deal',
 'figure',
 'coming',
 'expected',
 'matter',
 'editing',
 'run',
 'erotica',
 'ago',
 'potential',
 'depth',
 'pick',
 'wanting',
 'okay',
 'boy',
 'absolutely',
 'turned',
 'hour',
 'adult',
 'paranormal',
 'often',
 'decided',
 'ate',
 'length',
 'soon',
 'highly',
 'overall',
 'giving',
 'lover',
 'simply',
 'throughout',
 'pack',
 'usually',
 'difficult',
 'house',
 'wa',
 'across',
 'collection',
 'history',
 'hate',
 'face',
 'easily',
 'emotion',
 'sometimes',
 'supposed',
 'third',
 'hold',
 'ark',
 'top',
 'adventure',
 'event',
 'ont',
 'complete',
 'poor',
 'certainly',
 'learn',
 'ove',
 'save',
 'opinion',
 'spent',
 'bed',
 'secret',
 'ome',
 'death',
 'slow',
 'humor',
 'ad',
 'missing',
 'dream',
 'small',
 'play',
 'continue',
 'setting',
 'break',
 'attraction',
 'killer',
 'waiting',
 'sentence',
 'movie',
 'minute',
 'tried',
 'information',
 'plan',
 'ake',
 'realize',
 'aybe',
 'living',
 'extremely',
 'fight',
 'power',
 'wolf',
 'married',
 'question',
 'talk',
 'marriage',
 'surprised',
 'stay',
 'beautiful',
 'remember',
 'seen',
 'ike',
 'kill',
 'predictable',
 'gay',
 'suspense',
 'concept',
 'hese',
 'became',
 'involved',
 'excellent',
 'taking',
 'pay',
 'behind',
 'surprise',
 'called',
 'dark',
 'shifter',
 'rating',
 'emotional',
 'kid',
 'based',
 'met',
 'ok',
 'daughter',
 'amazing',
 'week',
 'four',
 'background',
 'mistake',
 'aspect',
 'finding',
 'group',
 'known',
 'middle',
 'form',
 'fell',
 'stuff',
 'body',
 'saying',
 'cute',
 'within',
 'ew',
 'immediately',
 'close',
 'room',
 'list',
 'example',
 'business',
 'downloaded',
 'loving',
 'murder',
 'cannot',
 'picture',
 'admit',
 'fit',
 'seeing',
 'willing',
 'working',
 'wonder',
 'early',
 'content',
 'clear',
 'important',
 'five',
 'connection',
 'bring',
 'etc',
 'share',
 'beyond',
 'ability',
 'taken',
 'magic',
 'paid',
 'previous',
 'level',
 'nfortunately',
 'desire',
 'son',
 'somewhat',
 'hoping',
 'editor',
 'choice',
 'ames',
 'saw',
 'exactly',
 'huge',
 'partner',
 'sequel',
 'original',
 'chemistry',
 'leaf',
 'return',
 'annoying',
 'forced',
 'piece',
 'ane',
 'special',
 'hurt',
 'becomes',
 'drawn',
 'hristmas',
 'act',
 'open',
 'expecting',
 'view',
 'realistic',
 'dragon',
 'spend',
 'flow',
 'ex',
 'brought',
 'number',
 'irst',
 'ade',
 'ready',
 'evil',
 'offer',
 'decides',
 'due',
 'till',
 'sorry',
 'tension',
 'using',
 'present',
 'war',
 'alex',
 'space',
 'force',
 'aa',
 'simple',
 'bother',
 'buying',
 'taste',
 'mostly',
 'building',
 'ick',
 'older',
 'quality',
 'honest',
 'conflict',
 'picked',
 'ould',
 'build',
 'weak',
 'caught',
 'fairly',
 'mentioned',
 'et',
 'element',
 'perhaps',
 'ar',
 'an',
 'ay',
 'alien',
 'personal',
 'control',
 'race',
 'demon',
 'serious',
 'graphic',
 'fine',
 'described',
 'unique',
 'rushed',
 'paper',
 'worked',
 'accept',
 'certain',
 'writes',
 'trouble',
 'angel',
 'zombie',
 'paragraph',
 'stupid',
 'ost',
 'grammar',
 'download',
 'hy',
 'ack',
 'science',
 'yes',
 'wrote',
 'amount',
 'decent',
 'fairy',
 'mention',
 'strange',
 'date',
 'confusing',
 'copy',
 'telling',
 'check',
 'added',
 'sound',
 'thrown',
 'parent',
 'filled',
 'classic',
 'trust',
 'struggle',
 'purchase',
 'exciting',
 'drama',
 'crazy',
 'held',
 'available',
 'horror',
 'protagonist',
 'agree',
 'including',
 'intriguing',
 'ead',
 'marry',
 'attempt',
 'dead',
 'encounter',
 'lake',
 'ax',
 'upon',
 'fear',
 'fully',
 'od',
 'silly',
 'whether',
 'personality',
 'typo',
 'boyfriend',
 'eally',
 'promise',
 'note',
 'car',
 'sad',
 'except',
 'eviewed',
 'talking',
 'theme',
 'straight',
 'menage',
 'thoroughly',
 'purchased',
 'actual',
 'hell',
 'ave',
 'oved',
 'meeting',
 'hit',
 'baby',
 'ridiculous',
 'police',
 'published',
 'worst',
 'passion',
 'odd',
 'game',
 'term',
 'rom',
 'hank',
 'focus',
 'develop',
 'gone',
 'effort',
 'unless',
 'edition',
 'sample',
 'particularly',
 'touch',
 'suddenly',
 'subject',
 'wedding',
 'typical',
 'prequel',
 'hooked',
 'escape',
 'oyfully',
 'single',
 'basic',
 'conversation',
 'cause',
 'pace',
 'determined',
 'blog',
 'awesome',
 'super',
 'art',
 'ebook',
 'th',
 'anyway',
 'flat',
 'fighting',
 'arc',
 'paced',
 'poorly',
 'apparently',
 'club',
 'realized',
 'heir',
 'protect',
 'basically',
 'belief',
 'nature',
 'decision',
 'introduced',
 'horrible',
 'seriously',
 'major',
 'historical',
 'knowing',
 'deep',
 'oo',
 'cut',
 'didnt',
 'animal',
 'reread',
 'lose',
 'serial',
 'interaction',
 'verall',
 'none',
 'heat',
 'wondering',
 'particular',
 'area',
 'recommended',
 'ride',
 'hristian',
 'stopped',
 'near',
 'bored',
 'engaging',
 'running',
 'moving',
 'worse',
 'danger',
 'difference',
 'confused',
 'voice',
 'pull',
 'ghost',
 'period',
 'ean',
 'en',
 'possible',
 'fantastic',
 'changed',
 'unbelievable',
 'party',
 'answer',
 'pain',
 'spoiler',
 'plenty',
 'imagine',
 'modern',
 'leaving',
 'ask',
 'wo',
 'reality',
 'orry',
 'brings',
 'ince',
 'self',
 'lady',
 'unter',
 'american',
 'ohn',
 'reference',
 'created',
 'honestly',
 'normally',
 'afraid',
 'decide',
 'location',
 'ight',
 'detective',
 'draw',
 'moved',
 'purpose',
 'apart',
 'freebie',
 'trilogy',
 'familiar',
 'journey',
 'weird',
 'killed',
 'lie',
 'lacking',
 'pa',
 'appears',
 'ship',
 'ho',
 'oul',
 'step',
 'cat',
 'keeping',
 'uke',
 'falling',
 'normal',
 'cop',
 'college',
 'company',
 'elly',
 'whats',
 'est',
 'door',
 'nglish',
 'jump',
 'missed',
 'skip',
 'final',
 'omance',
 'current',
 'happily',
 'despite',
 'crime',
 'late',
 'speak',
 'team',
 'watching',
 'killing',
 'grab',
 'lived',
 'laugh',
 'aylee',
 'starting',
 'describe',
 'nearly',
 'thriller',
 'throw',
 'outside',
 'ere',
 'conclusion',
 'low',
 'battle',
 'product',
 'walk',
 'lust',
 'ice',
 'eat',
 'truth',
 'turning',
 'rich',
 'imagination',
 'comment',
 'pleasure',
 'travel',
 'oth',
 'consider',
 'nce',
 'satisfying',
 'formatting',
 'installment',
 'younger',
 'included',
 'doubt',
 'received',
 'im',
 'introduction',
 'explanation',
 'imon',
 'inside',
 'explicit',
 'towards',
 'terrible',
 'looked',
 'sounded',
 'disappointing',
 'society',
 'obvious',
 'enjoying',
 'result',
 'ord',
 'meant',
 'rape',
 'neither',
 'tired',
 'claim',
 'physical',
 'member',
 'obviously',
 'article',
 'smart',
 'teenager',
 'adam',
 'research',
 'attack',
 'attracted',
 'black',
 'violence',
 'solid',
 'realizes',
 'appreciate',
 'role',
 'sleep',
 'soul',
 'friendship',
 'literally',
 'gotten',
 'allow',
 'began',
 'incredibly',
 'earth',
 'common',
 'ee',
 'happening',
 'hough',
 'enry',
 'usual',
 'mma',
 'win',
 'catch',
 'putting',
 'magazine',
 'om',
 'intense',
 'ed',
 'cold',
 'perspective',
 'ing',
 'constantly',
 'slightly',
 'ale',
 'section',
 'create',
 'aside',
 ...]

In [71]:
model.corpus_count

9600

#### using AvgWord2Vec on top of it

In [72]:
import numpy as np

def avg_word2vec(doc):
    vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [73]:
!pip install tqdm

Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)

In [74]:
from tqdm import tqdm

In [75]:
## applying avgword2vec to entire sentence
X = []
for i in tqdm(range(len(words))):
  X.append(avg_word2vec(words[i]))

100%|██████████| 9600/9600 [00:39<00:00, 245.62it/s]

In [76]:
len(X)

9600

In [77]:
## Independent features
X_new = np.array(X)

In [81]:
X_new.shape

(9600, 100)

In [82]:
## 100 dimension vector
X_new[0].shape

(100,)

In [88]:
y_new = y_train

#### 4. Train with ML Algos --> Using Gaussian Naive Bayes with Word2Vec

In [89]:
from sklearn.naive_bayes import GaussianNB
nb_model_word2vec = GaussianNB().fit(X_new, y_new)

In [90]:
words_test = []
for sent in X_test:
    sent_token = sent_tokenize(sent)
    for word in sent_token:
        words_test.append(simple_preprocess(word))


X_test_word2vec = []
for i in tqdm(range(len(words_test))):
    X_test_word2vec.append(avg_word2vec(words_test[i]))

X_test_word2vec = np.array(X_test_word2vec)

100%|██████████| 2400/2400 [00:04<00:00, 544.55it/s]

In [91]:
from sklearn.metrics import accuracy_score, confusion_matrix
y_pred_word2vec = nb_model_word2vec.predict(X_test_word2vec)

print("Word2Vec accuracy:", accuracy_score(y_test, y_pred_word2vec))
print("Confusion Matrix for Word2Vec:")
print(confusion_matrix(y_test, y_pred_word2vec))

Word2Vec accuracy: 0.6729166666666667
Confusion Matrix for Word2Vec:
[[ 559  228]
 [ 557 1056]]