#### BOW AND TF-IDF AND MACHINE LEARNING

1. Preprocessing and Cleaning
2. Train Test Split
3. BOW and TF-IDF (Sentences --> vectors) (Prevent data leakage)
4. Train our model

In [8]:
!wget https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/SpamClassifier-master/smsspamcollection/SMSSpamCollection
import pandas as pd
messages = pd.read_csv("SMSSpamCollection", sep='\t', names=["label", "message"])
messages.head()

--2026-04-07 10:47:21--  https://raw.githubusercontent.com/krishnaik06/Complete-Data-Science-With-Machine-Learning-And-NLP-2024/main/26-CompleteNLP%20For%20Machine%20Learning/Practicals/SpamClassifier-master/smsspamcollection/SMSSpamCollection
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.109.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.109.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 477907 (467K) [text/plain]
Saving to: ‘SMSSpamCollection.1’

SMSSpamCollection.1 100%[===================>] 466.71K  --.-KB/s    in 0.04s

2026-04-07 10:47:21 (11.8 MB/s) - ‘SMSSpamCollection.1’ saved [477907/477907]

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

## Data cleaning and preprocessing

In [9]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [11]:
corpus = []
stop_words = set(stopwords.words('english'))
for msg in messages['message']:
  review= re.sub('[^a-zA-Z]', ' ', msg)
  review = review.lower()
  review = review.split()

  review = [ps.stem(word) for word in review if word not in stop_words]
  review = ' '.join(review)
  corpus.append(review)

In [12]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promis wont take help grant fulfil promis wonder bless time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt messag click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watch',
 'eh u rememb spell name ye v naughti make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur nation team eg england tri wale scotland txt poboxox w wq',
 'serious spell name',
 'go tri month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch alreadi',
 'ffffffffff alright way meet sooner',
 'forc eat slice realli hungri tho suck mark get worri know sick turn pizza lol',
 'lol alway convinc',
 'catch bu fri egg make tea eat mom left dinner feel love',
 'back amp pack car let know room',
 'ahhh work vagu rememb feel like lol',
 'wait still clear sure sarcast x want live us',
 'yeah got v apologet n fallen actin like spoilt child got caught till go badli cheer',
 'k tell anyth',
 'fear faint housework quick cuppa',
 'thank subscript rington uk mobil charg month pleas confirm repli ye repli charg',
 'yup ok go home look time msg xuhui go learn nd may lesson',
 'oop let know roommat done',
 'see letter b car',
 'anyth lor u decid',
 'hello saturday go text see decid anyth tomo tri invit anyth',
 'pl go ahead watt want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummi',
 'rodger burn msg tri call repli sm free nokia mobil free camcord pleas call deliveri tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call messag miss call',
 'get hep b immunis nigeria',
 'fair enough anyth go',
 'yeah hope tyler could mayb ask around bit',
 'u know stubborn even want go hospit kept tell mark weak sucker hospit weak sucker',
 'think first time saw class',
 'gram usual run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride earli tomorrow morn crash place tonight',
 'wow never realiz embarass accomod thought like sinc best could alway seem happi cave sorri give sorri offer sorri room embarass',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end repli end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'sorri call later meet',
 'tell reach',
 'ye gauti sehwag odi seri',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situat seeker',
 'part check iq',
 'sorri roommat took forev ok come',
 'ok lar doubl check wif da hair dresser alreadi said wun cut v short said cut look nice',
 'valu custom pleas advis follow recent review mob award bonu prize call',
 'today song dedic day song u dedic send ur valuabl frnd first rpli',
 'urgent ur award complimentari trip eurodisinc trav aco entri claim txt di morefrmmob shracomorsglsuplt ls aj',
 'hear new divorc barbi come ken stuff',
 'plane give month end',
 'wah lucki man save money hee',
 'finish class',
 'hi babe im home wanna someth xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'that cool gentleman treat digniti respect',
 'like peopl much shi pa',
 'oper lt gt',
 'still look job much ta earn',
 'sorri call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket done alreadi use multi',
 'ye start send request make pain came back back bed doubl coin factori gotta cash nitro',
 'realli still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch someth',
 'sorri pain ok meet anoth night spent late afternoon casualti mean done stuff moro includ time sheet sorri',
 'smile pleasur smile pain smile troubl pour like rain smile sum hurt u smile becoz someon still love see u smile',
 'pleas call custom servic repres pm guarante cash prize',
 'havent plan buy later check alreadi lido got show e afternoon u finish work alreadi',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'watch telugu movi wat abt u',
 'see finish load loan pay',
 'hi wk ok hol ye bit run forgot hairdress appoint four need get home n shower beforehand caus prob u',
 'see cup coffe anim',
 'pleas text anymor noth els say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy gone drive test yet',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'wow right mean guess gave boston men chang search locat nyc someth chang cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thank lot wish birthday thank make birthday truli memor',
 'aight hit get cash',
 'would ip address test consid comput minecraft server',
 'know grumpi old peopl mom like better lie alway one play joke',
 'dont worri guess busi',
 'plural noun research',
 'go dinner msg',
 'ok wif co like tri new thing scare u dun like mah co u said loud',
 'gent tri contact last weekend draw show prize guarante call claim code k valid hr ppm',
 'wa ur openin sentenc formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'winner u special select receiv holiday flight inc speak live oper claim p min',
 'goodo ye must speak friday egg potato ratio tortilla need',
 'hmm uncl inform pay school directli pl buy food',
 'privat account statement show unredeem bonu point claim call identifi code expir',
 'urgent mobil award bonu caller prize final tri contact u call landlin box wr c ppm',
 'new address appl pair malarki',
 'today voda number end select receiv award match pleas call quot claim code standard rate app',
 'go sao mu today done',
 'predict wat time finish buy',
 'good stuff',
 'know yetund sent money yet sent text bother send dont involv anyth impos anyth first place apologis',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pl accomod',
 'first answer question',
 'sunshin quiz wkli q win top soni dvd player u know countri algarv txt ansr sp tyron',
 'want get laid tonight want real dog locat sent direct ur mob join uk largest dog network bt txting gravel nt ec p msg p',
 'haf msn yiju hotmail com',
 'call meet',
 'check room befor activ',
 'rcv msg chat svc free hardcor servic text go u get noth u must age verifi yr network tri',
 'got c lazi type forgot lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt thought nver get tire littl thing lovabl person coz somtim littl thing occupi biggest part heart gud ni',
 'know pl open back',
 'ye see ya dot',
 'what staff name take class us',
 'freemsg repli text randi sexi femal live local luv hear u netcollex ltd p per msg repli stop end',
 'ummma call check life begin qatar pl pray hard',
 'k delet contact',
 'sindu got job birla soft',
 'wine flow never',
 'yup thk cine better co need go plaza mah',
 'ok ur typic repli',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'everywher dirt floor window even shirt sometim open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done becom one',
 'aaooooright work',
 'leav hous',
 'hello love get interview today happi good boy think miss',
 'custom servic annonc new year deliveri wait pleas call arrang deliveri',
 'winner u special select receiv cash holiday flight inc speak live oper claim',
 'keep safe need miss alreadi envi everyon see real life',
 'new car hous parent new job hand',
 'love excit day spend make happi',
 'pl stop bootydeli f invit friend repli ye see www sm ac u bootydeli stop send stop frnd',
 'bangbab ur order way u receiv servic msg download ur content u goto wap bangb tv ur mobil internet servic menu',
 'place ur point e cultur modul alreadi',
 'urgent tri contact last weekend draw show prize guarante call claim code valid hr',
 'hi frnd best way avoid missunderstd wit belov one',
 'great escap fanci bridg need lager see tomo',
 'ye complet form clark also utter wast',
 'sir need axi bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloodi hell cant believ forgot surnam mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlo make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt repli let know log',
 'hi spoke maneesha v like know satisfi experi repli toll free ye',
 'lift hope offer money need especi end month approach hurt studi anyway gr weekend',
 'lol u trust',
 'ok gentleman treat digniti respect',
 'guy close',
 'go noth great bye',
 'hello handsom find job lazi work toward get back net mummi boytoy miss',
 'haha awesom minut',
 'pleas call custom servic repres freephon pm guarante cash prize',
 'got xma radio time get',
 'ju reach home go bath first si use net tell u finish k',
 'uniqu enough find th august www areyouuniqu co uk',
 'sorri join leagu peopl dont keep touch mean great deal friend time even great person cost great week',
 'hi final complet cours',
 'stop howev suggest stay someon abl give or everi stool',
 'hope settl new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person stori',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloodi babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finish colleg txt u finish u love kate xxx',
 'account refil success inr lt decim gt keralacircl prepaid account balanc rs lt decim gt transact id kr lt gt',
 'goodmorn sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa said happi b day boss felt special askd lunch lunch invit apart went',
 'aight yo dat straight dogg',
 'pleas give us connect today lt decim gt refund bill',
 'shoot big load get readi',
 'bruv hope great break reward semest',
 'home alway chat',
 'k k good studi well',
 'yup noe leh',
 'sound great home',
 'final match head toward draw predict',
 'tire slept well past night',
 'easi ah sen got select mean good',
 'take exam march',
 'yeah think use gt atm regist sure anyway help let know sure readi',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use os copi import file system give repair shop',
 'sorri call later',
 'u say leh cours noth happen lar say v romant ju bit lor thk e nite sceneri nice leh',
 'new mobil must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would realli appreci call need someon talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo ari',
 'hey compani elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happi morn',
 'dear good morn',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorri batteri die yeah',
 'ye tv alway avail work place',
 'text meet someon sexi today u find date even flirt u join p repli name age eg sam msg recd thirtyeight penc',
 'print oh lt gt come upstair',
 'ill littl closer like bu stop street',
 'wil reach',
 'new theori argument win situat lose person dont argu ur friend kick amp say alway correct',
 'u secret admir look make contact u find r reveal think ur special call',
 'tomarrow final hear laptop case cant',
 'pleassssssseeeee tel v avent done sportsx',
 'okay shine meant sign sound better',
 'although told u dat baig face watch realli like e watch u gave co fr u thanx everyth dat u done today touch',
 'u rememb old commerci',
 'late said websit dont slipper',
 'ask call ok',
 'kalli wont bat nd inning',
 'didnt work oh ok goodnight fix readi time wake dearli miss good night sleep',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovabl bcum angri wid u dnt take serious coz angri childish n true way show deep affect care n luv kettoda manda nice day da',
 '',
 'up day also ship compani take wk way usp take week get lag may bribe nipost get stuff',
 'back lemm know readi',
 'necessarili expect done get back though headin',
 'mmm yummi babe nice jolt suzi',
 'lover need',
 'tri contact repli offer video handset anytim network min unlimit text camcord repli call',
 'park next mini come today think',
 'yup',
 'anyway go shop co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey realli horni want chat see nake text hot text charg pm unsubscrib text stop',
 'dint come us',
 'wana plan trip sometm',
 'sure yet still tri get hold',
 'ur rington servic chang free credit go club mobil com choos content stop txt club stop p wk club po box mk wt',
 'evo download flash jealou',
 'rington club get uk singl chart mobil week choos top qualiti rington messag free charg',
 'come mu sort narcot situat',
 'night end anoth day morn come special way may smile like sunni ray leav worri blue blue bay',
 'hmv bonu special pound genuin hmv voucher answer easi question play send hmv info www percent real com',
 'usf guess might well take car',
 'object bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesom see bit',
 'sent type food like',
 'done hand celebr full swing yet',
 'got call tool',
 'wen u miss someon person definit special u person special miss keep touch gdeve',
 'ok ask money far',
 'oki',
 'yeah think usual guy still pass last night get ahold anybodi let know throw',
 'k might come tonight class let earli',
 'ok',
 'hi babi im cruisin girl friend r u give call hour home that alright fone fone love jenni xxx',
 'life mean lot love life love peopl life world call friend call world ge',
 'dear shall mail tonit busi street shall updat tonit thing look ok varunnathu edukkukaye raksha ollu good one real sens',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam work',
 'oop got bit',
 'much buzi',
 'accident delet messag resend pleas',
 'mobil custom may claim free camera phone upgrad pay go sim card loyalti call offer end thfeb c appli',
 'unless situat go gurl would appropri',
 'hurt teas make cri end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pl send messag',
 'need coffe run tomo believ time week alreadi',
 'awesom rememb last time got somebodi high first time diesel v',
 'shit realli shock scari cant imagin second def night u think somewher could crash night save taxi',
 'oh way food fridg want go meal tonight',
 'womdarful actor',
 'sm ac blind date u rodd aberdeen unit kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jo ask u wana meet',
 'lol ye friendship hang thread caus u buy stuff',
 'themob check newest select content game tone gossip babe sport keep mobil fit funki text wap',
 'garag key bookshelf',
 'today accept day u accept brother sister lover dear best clo lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rpli mean enemi',
 'think ur smart win week weekli quiz text play cs winnersclub po box uz gbp week',
 'say give call friend got money definit buy end week',
 'hi way u day normal way real ur uniqu hope know u rest mylif hope u find wot lost',
 'made day great day',
 'k k advanc happi pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'realli dude friend afraid',
 'decemb mobil mth entitl updat latest colour camera mobil free call mobil updat co free',
 'coffe cake guess',
 'merri christma babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co buse hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewher get touch weekend plan take flight good week',
 'problem',
 'call messag miss call',
 'hi da today class',
 'say good sign well know track record read women',
 'cool text park',
 'read text sent meant joke read light',
 'k k apo k good movi',
 'mayb could get book tomo return immedi someth',
 'call germani penc per minut call fix line via access number prepay direct access',
 'chanc might evapor soon violat privaci steal phone number employ paperwork cool pleas contact report supervisor',
 'valentin day special win quiz take partner trip lifetim send go p msg rcvd custcar',
 'ta daaaaa home babe still',
 'cool come havent wine dine',
 'sleep surf',
 'sorri call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happi read one wiv hello carolin end favourit bless',
 'u hide stranger',
 'interest like',
 'sister clear two round birla soft yesterday',
 'gudnit tc practic go',
 'di yiju ju saw ur mail case huim havent sent u num di num',
 'one small prestig problem',
 'fanci shag interest sextextuk com txt xxuk suzi txt cost per msg tnc websit x',
 'check realli miss see jeremiah great month',
 'nah help never iphon',
 'car hour half go apeshit',
 'today sorri day ever angri ever misbehav hurt plz plz slap urself bcoz ur fault basic good',
 'yo guy ever figur much need alcohol jay tri figur much safe spend weed',
 'lt gt ish minut minut ago wtf',
 'thank call forgot say happi onam sirji fine rememb met insur person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratul ur award cd voucher gift guarante free entri wkli draw txt music tnc www ldew com win ppmx age',
 'ur cash balanc current pound maxim ur cash send cash p msg cc hg suit land row w j hl',
 'actor work work even sleep late sinc unemploy moment alway sleep late unemploy everi day saturday',
 'hello got st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey statu right',
 'busi tri finish new year look forward final meet',
 'good afternoon sunshin dawn day refresh happi aliv breath air smile think love alway',
 'well know z take care worri',
 'updat xma offer latest motorola sonyericsson nokia free bluetooth doubl min txt orang call mobileupd call optout f q',
 'discount code rp stop messag repli stop www regalportfolio co uk custom servic',
 'wat uniform get',
 'cool text readi',
 'hello boytoy geeee miss alreadi woke wish bed cuddl love',
 'spoil bed well',
 'go bath msg next lt gt min',
 'cant keep talk peopl sure pay agre price pl tell want realli buy much will pay',
 'thank rington order refer charg gbp per week unsubscrib anytim call custom servic',
 'say happen',
 'could seen recognis face',
 'well lot thing happen lindsay new year sigh bar ptbo blue heron someth go',
 'keep payasam rinu bring',
 'taught ranjith sir call sm like becau he verifi project prabu told today pa dont mistak',

## Create a Bag Of Words(BOW)

In [43]:
## output features
y = pd.get_dummies(messages['label'])
y = y.iloc[:,0].values.astype(int)

In [44]:
y

array([1, 1, 0, ..., 1, 1, 1])

In [45]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus,y,test_size=0.20)

### Converting sentence to vector (applying BOW)

In [50]:
from sklearn.feature_extraction.text import CountVectorizer
## for binary BOW enable binary = True
cv = CountVectorizer(max_features=100,binary=True)

In [51]:
len(X_train),len(y_train)

(4457, 4457)

In [52]:
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [53]:
X_train.shape

(4457, 100)

In [55]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [57]:
import numpy as np
np.set_printoptions(edgeitems=30,linewidth=100000,formatter=dict(float=lambda x: "%.3g" %x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, ..., 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0]])

## Trying it with the lemmatization

In [17]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger_eng')
lemmatizer = WordNetLemmatizer()

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.

In [18]:
stop_words = set(stopwords.words('english'))
def  get_word_pos(tag):
  if tag.startswith('J'):
    return wordnet.ADJ
  elif tag.startswith('V'):
    return wordnet.VERB
  elif tag.startswith('N'):
        return wordnet.NOUN
  elif tag.startswith('R'):
      return wordnet.ADV
  else:
      return wordnet.NOUN

corpus = []
stop_words = set(stopwords.words('english'))
for msg in messages['message']:
  review= re.sub('[^a-zA-Z]', ' ', msg)
  review = review.lower()
  review = review.split()

  tokens = nltk.pos_tag(review)

  review = [
    lemmatizer.lemmatize(word,get_word_pos(pos_tag))
    for word,pos_tag in tokens
    if word not in stop_words
  ]
  review = ' '.join(review)
  corpus.append(review)

In [19]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine get amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf live around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner value network customer select receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitle update late colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cry enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather promise wont take help grant fulfil promise wonderful blessing time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watching',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur national team eg england try wale scotland txt poboxox w wq',
 'seriously spell name',
 'go try month ha ha joke',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'force eat slice really hungry tho suck mark get worry know sick turn pizza lol',
 'lol always convincing',
 'catch bus fry egg make tea eat mom leave dinner feel love',
 'back amp pack car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live u',
 'yeah get v apologetic n fall actin like spoilt child get catch till go badly cheer',
 'k tell anything',
 'fear faint housework quick cuppa',
 'thanks subscription ringtone uk mobile charge month please confirm reply yes reply charge',
 'yup ok go home look timing msg xuhui go learn nd may lesson',
 'oops let know roommate do',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decide anything tomo try invite anything',
 'pls go ahead watts want sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg try call reply sm free nokia mobile free camcorder please call delivery tomorrow',
 'see',
 'great hope like man well endow lt gt inch',
 'call message miss call',
 'get hep b immunisation nigeria',
 'fair enough anything go',
 'yeah hopefully tyler could maybe ask around bit',
 'u know stubborn even want go hospital keep tell mark weak sucker hospital weak sucker',
 'think first time saw class',
 'gram usually run like lt gt half eighth smart though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crash place tonight',
 'wow never realize embarassed accomodations think like since best could always seem happy cave sorry give sorry offer sorry room embarassing',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pas call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meeting',
 'tell reach',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain kill',
 'ha ha ha good joke girl situation seeker',
 'part check iq',
 'sorry roommate take forever ok come',
 'ok lar double check wif da hair dresser already say wun cut v short say cut look nice',
 'value customer please advise follow recent review mob award bonus prize call',
 'today song dedicate day song u dedicate send ur valuable frnds first rply',
 'urgent ur award complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt l aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finish class',
 'hi babe im home wanna something xx',
 'k k perform',
 'u call',
 'wait machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still look job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u get yo need ticket one jacket do already use multis',
 'yes start send request make pain come back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spend late afternoon casualty mean do stuff moro include time sheet sorry',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smile',
 'please call customer service representative pm guaranteed cash prize',
 'havent planning buy later check already lido get show e afternoon u finish work already',
 'free ringtone wait collect simply text password mix verify get usher britney fml po box mk h ppw',
 'watch telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bit run forget hairdresser appointment four need get home n shower beforehand cause prob u',
 'see cup coffee animation',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still look car buy go drive test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'wow right mean guess give boston men change search location nyc something change cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thanks lot wish birthday thanks make birthday truly memorable',
 'aight hit get cash',
 'would ip address test consider computer minecraft server',
 'know grumpy old people mom like good lie always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'go dinner msg',
 'ok wif cos like try new thing scar u dun like mah co u say loud',
 'gent try contact last weekend draw show prize guaranteed call claim code k valid hr ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happen',
 'enter cabin pa say happy b day bos felt special askd lunch lunch invite apartment go',
 'winner u specially select receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla need',
 'hmm uncle inform pay school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expire',
 'urgent mobile award bonus caller prize final try contact u call landline box wr c ppm',
 'new address apple pair malarky',
 'today voda number end select receive award match please call quote claim code standard rate app',
 'go sao mu today do',
 'predict wat time finish buying',
 'good stuff',
 'know yetunde send money yet send text bother send dont involve anything impose anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get lay tonight want real dogging location send direct ur mob join uk large dog network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activity',
 'rcv msg chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'get c lazy type forget lect saw pouch like v nice',
 'k text way',
 'sir wait mail',
 'swt think nver get tire little thing lovable person coz somtimes little thing occupy big part heart gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name take class u',
 'freemsg reply text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k delete contact',
 'sindu get job birla soft',
 'wine flow nevering',
 'yup thk cine well co need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'everywhere dirt floor window even shirt sometimes open mouth come flow dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time do become one',
 'aaooooright work',
 'leave house',
 'hello love get interview today happy good boy think miss',
 'customer service annoncement new year delivery wait please call arrange delivery',
 'winner u specially select receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excited day spend make happy',
 'pls stop bootydelious f invite friend reply yes see www sms ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent try contact last weekend draw show prize guaranteed call claim code valid hr',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure get time hop ard ya go free abt muz call u discuss liao',
 'time come later',
 'bloody hell cant believe forget surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know get money carlos make call',
 'u still go mall',
 'turn friend stay whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi speak maneesha v like know satisfy experience reply toll free yes',
 'lift hope offer money need especially end month approach hurt study anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'go nothing great bye',
 'hello handsome find job lazy working towards get back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guaranteed cash prize',
 'get xmas radio time get',
 'jus reach home go bathe first si use net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry join league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally complete course',
 'stop however suggest stay someone able give or every stool',
 'hope settle new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u get person story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate even hope see tomorrow bit bloody babyjontet txt back u xxx',
 'find enc lt gt',
 'send lt gt buck',
 'hello darlin ive finish college txt u finish u love kate xxx',
 'account refill successfully inr lt decimal gt keralacircle prepaid account balance rs lt decimal gt transaction id kr lt gt',
 'goodmorning sleep ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'enter cabin pa say happy b day bos felt special askd lunch lunch invite apartment go',
 'aight yo dat straight dogg',
 'please give u connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break rewarding semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match heading towards draw prediction',
 'tire slept well past night',
 'easy ah sen get select mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'os call ubandu run without instal hard disk use o copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh',
 'new mobile must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo follow ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear go rubber place',
 'sorry battery die yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny',
 'print oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation lose person dont argue ur friend kick amp say always correct',
 'u secret admirer look make contact u find r reveal think ur special call',
 'tomarrow final hearing laptop case cant',
 'pleassssssseeeeee tel v avent do sportsx',
 'okay shin mean sign sound well',
 'although tell u dat baig face watch really like e watch u give co fr u thanx everything dat u do today touch',
 'u remember old commercial',
 'late say website dont slipper',
 'ask call ok',
 'kallis wont bat nd inning',
 'didnt work oh ok goodnight fix ready time wake dearly miss good night sleep',
 'congratulation ur award cd voucher gift guarantee free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way show deep affection care n luv kettoda manda nice day da',
 '',
 'ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect do get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'try contact reply offer video handset anytime network min unlimited text camcorder reply call',
 'park next mini come today think',
 'yup',
 'anyway go shopping cos si do yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charge pm unsubscribe text stop',
 'dint come u',
 'wana plan trip sometme',
 'sure yet still try get hold',
 'ur ringtone service change free credit go club mobile com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sort narcotic situation',
 'night end another day morning come special way may smile like sunny ray leave worry blue blue bay',
 'hmv bonus special pound genuine hmv voucher answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf come',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bit',
 'send type food like',
 'do hand celebration full swing yet',
 'get call tool',
 'wen u miss someone person definitely special u person special miss keep touch gdeve',
 'ok ask money far',
 'okie',
 'yeah think usual guy still pass last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friends call world ge',
 'dear shall mail tonite busy street shall update tonite thing look ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey tell name gautham ah',
 'haf u find feel stupid da v cam work',
 'oops get bit',
 'much buzy',
 'accidentally delete message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rise grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time get somebody high first time diesel v',
 'shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sm ac blind date u rodds aberdeen united kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hang thread cause u buy stuff',
 'themob check new selection content game tone gossip babe sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play c winnersclub po box uz gbp week',
 'say give call friend get money definitely buy end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lose',
 'make day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk get lo oso forget liao',
 'really dude friend afraid',
 'december mobile mths entitle update late colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message miss call',
 'hi da today class',
 'say good sign well know track record read woman',
 'cool text park',
 'read text send meant joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany penny per minute call fixed line via access number prepayment direct access',
 'chance might evaporate soon violate privacy steal phone number employer paperwork cool please contact report supervisor',
 'valentine day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent win din',
 'sleeping surfing',
 'sorry call later',
 'u call right call hand phone',
 'ok great thanx lot',
 'take post come must text happy read one wiv hello caroline end favourite bless',
 'u hide stranger',
 'interested like',
 'sister clear two round birla soft yesterday',
 'gudnite tc practice go',
 'dis yijue jus saw ur mail case huiming havent send u num dis num',
 'one small prestige problem',
 'fancy shag interested sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'check really miss see jeremiah great month',
 'nah help never iphone',
 'car hour half go apeshit',
 'today sorry day ever angry ever misbehave hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay try figure much safely spend weed',
 'lt gt ish minute minute ago wtf',
 'thank call forgot say happy onam sirji fine remember meet insurance person meet qatar insha allah rakhesh ex tata aig join tissco tayseer',
 'congratulation ur award cd voucher gift guarantee free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',
 'actor work work evening sleep late since unemployed moment always sleep late unemployed every day saturday',
 'hello get st andrew boy long way cold keep post',
 'ha ha cool cool chikku chikku db',
 'oh ok prob',
 'check audrey status right',
 'busy try finish new year look forward finally meet',
 'good afternoon sunshine dawn day refresh happy alive breathe air smile think love always',
 'well know z take care worry',

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
## for binary BOW enable binary = True
cv = CountVectorizer(max_features=100,binary=True)

In [21]:
X = cv.fit_transform(corpus).toarray()

In [22]:
X.shape

(5572, 100)

In [23]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
cv.vocabulary_

{'go': np.int64(23),
 'great': np.int64(25),
 'get': np.int64(21),
 'wat': np.int64(90),
 'ok': np.int64(59),
 'free': np.int64(19),
 'win': np.int64(94),
 'text': np.int64(79),
 'txt': np.int64(86),
 'say': np.int64(69),
 'already': np.int64(0),
 'think': np.int64(81),
 'hey': np.int64(28),
 'week': np.int64(92),
 'back': np.int64(3),
 'like': np.int64(40),
 'still': np.int64(75),
 'send': np.int64(71),
 'even': np.int64(16),
 'friend': np.int64(20),
 'prize': np.int64(65),
 'claim': np.int64(7),
 'call': np.int64(4),
 'mobile': np.int64(50),
 'late': np.int64(36),
 'co': np.int64(8),
 'home': np.int64(30),
 'want': np.int64(89),
 'today': np.int64(83),
 'cash': np.int64(6),
 'day': np.int64(13),
 'reply': np.int64(67),
 'www': np.int64(96),
 'right': np.int64(68),
 'take': np.int64(77),
 'time': np.int64(82),
 'message': np.int64(47),
 'com': np.int64(9),
 'oh': np.int64(58),
 'yes': np.int64(99),
 'make': np.int64(45),
 'way': np.int64(91),
 'feel': np.int64(17),
 'dont': np.int64(15),
 'miss': np.int64(49),
 'ur': np.int64(87),
 'try': np.int64(85),
 'da': np.int64(12),
 'lor': np.int64(42),
 'meet': np.int64(46),
 'really': np.int64(66),
 'know': np.int64(34),
 'lol': np.int64(41),
 'leave': np.int64(38),
 'love': np.int64(43),
 'let': np.int64(39),
 'work': np.int64(95),
 'wait': np.int64(88),
 'yeah': np.int64(97),
 'tell': np.int64(78),
 'please': np.int64(63),
 'msg': np.int64(52),
 'see': np.int64(70),
 'pls': np.int64(64),
 'need': np.int64(54),
 'tomorrow': np.int64(84),
 'hope': np.int64(31),
 'well': np.int64(93),
 'lt': np.int64(44),
 'gt': np.int64(26),
 'ask': np.int64(1),
 'keep': np.int64(33),
 'morning': np.int64(51),
 'happy': np.int64(27),
 'sorry': np.int64(74),
 'give': np.int64(22),
 'new': np.int64(55),
 'find': np.int64(18),
 'year': np.int64(98),
 'later': np.int64(37),
 'pick': np.int64(62),
 'good': np.int64(24),
 'come': np.int64(10),
 'hi': np.int64(29),
 'babe': np.int64(2),
 'im': np.int64(32),
 'much': np.int64(53),
 'stop': np.int64(76),
 'one': np.int64(60),
 'night': np.int64(56),
 'service': np.int64(72),
 'dear': np.int64(14),
 'thing': np.int64(80),
 'contact': np.int64(11),
 'last': np.int64(35),
 'min': np.int64(48),
 'number': np.int64(57),
 'sleep': np.int64(73),
 'care': np.int64(5),
 'phone': np.int64(61)}

## Implementing this using NGrams (IMP)

In [64]:
## creating the bag of words model with ngram
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))

In [65]:
X = cv.fit_transform(corpus).toarray()

In [66]:
cv.vocabulary_

{'free entry': np.int64(32),
 'claim call': np.int64(18),
 'call claim': np.int64(3),
 'free call': np.int64(31),
 'chance win': np.int64(17),
 'txt word': np.int64(90),
 'let know': np.int64(53),
 'go home': np.int64(35),
 'please call': np.int64(67),
 'lt gt': np.int64(59),
 'want go': np.int64(97),
 'like lt': np.int64(54),
 'like lt gt': np.int64(55),
 'sorry call': np.int64(82),
 'call later': np.int64(11),
 'sorry call later': np.int64(83),
 'ur award': np.int64(91),
 'come back': np.int64(22),
 'call customer': np.int64(4),
 'customer service': np.int64(24),
 'cash prize': np.int64(16),
 'call customer service': np.int64(5),
 'po box': np.int64(70),
 'try contact': np.int64(88),
 'draw show': np.int64(28),
 'show prize': np.int64(81),
 'valid hr': np.int64(95),
 'draw show prize': np.int64(29),
 'select receive': np.int64(78),
 'private account': np.int64(72),
 'account statement': np.int64(0),
 'call identifier': np.int64(6),
 'identifier code': np.int64(48),
 'private account statement': np.int64(73),
 'call identifier code': np.int64(7),
 'urgent mobile': np.int64(94),
 'call landline': np.int64(10),
 'wat time': np.int64(98),
 'ur mob': np.int64(93),
 'gud ni': np.int64(44),
 'new year': np.int64(63),
 'send stop': np.int64(80),
 'get back': np.int64(34),
 'co uk': np.int64(21),
 'nice day': np.int64(64),
 'lt decimal': np.int64(57),
 'decimal gt': np.int64(26),
 'lt decimal gt': np.int64(58),
 'good morning': np.int64(37),
 'ur friend': np.int64(92),
 'good night': np.int64(38),
 'reply call': np.int64(77),
 'last night': np.int64(52),
 'camera phone': np.int64(15),
 'pick phone': np.int64(66),
 'pls send': np.int64(68),
 'send message': np.int64(79),
 'pls send message': np.int64(69),
 'great day': np.int64(39),
 'suite land': np.int64(84),
 'land row': np.int64(51),
 'suite land row': np.int64(85),
 'good afternoon': np.int64(36),
 'take care': np.int64(86),
 'call mobileupd': np.int64(12),
 'call optout': np.int64(13),
 'gt min': np.int64(41),
 'lt gt min': np.int64(60),
 'txt stop': np.int64(89),
 'date service': np.int64(25),
 'pobox wq': np.int64(71),
 'prize guarantee': np.int64(75),
 'guarantee call': np.int64(42),
 'call land': np.int64(8),
 'land line': np.int64(49),
 'line claim': np.int64(56),
 'claim valid': np.int64(19),
 'prize guarantee call': np.int64(76),
 'guarantee call land': np.int64(43),
 'call land line': np.int64(9),
 'land line claim': np.int64(50),
 'claim valid hr': np.int64(20),
 'gt lt': np.int64(40),
 'hope good': np.int64(47),
 'free text': np.int64(33),
 'prize claim': np.int64(74),
 'nd attempt': np.int64(62),
 'attempt contact': np.int64(1),
 'ok lor': np.int64(65),
 'want come': np.int64(96),
 'every week': np.int64(30),
 'come home': np.int64(23),
 'happy new': np.int64(45),
 'happy new year': np.int64(46),
 'national rate': np.int64(61),
 'week txt': np.int64(99),
 'tell ur': np.int64(87),
 'await collection': np.int64(2),
 'dont know': np.int64(27),
 'call per': np.int64(14)}

In [67]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

## create TF-IDF model

In [71]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)


# Features
tv = TfidfVectorizer(max_features=2500, ngram_range=(1,2))
X_train = tv.fit_transform(corpus).toarray()
X_test = tv.transform(X_test).toarray()

In [72]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.268, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.272, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.434, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0.196, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.387, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [73]:
labels = []
for line in messages:
    parts = line.split('\t', 1)

    if len(parts) == 2:   # only valid lines
        label, text = parts
        labels.append(label)
        corpus.append(text)
    else:
        print("Skipped:", line)  # debug

Skipped: label
Skipped: message

In [77]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

# Features
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(messages['message'])

# Labels (clean way)
y = messages['label'].map({'ham': 0, 'spam': 1}).values

# Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [78]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 74169 stored elements and shape (5572, 8713)>

In [79]:
tv.vocabulary_

{'go': np.int64(804),
 'point': np.int64(1611),
 'crazy': np.int64(440),
 'available': np.int64(112),
 'bugis': np.int64(217),
 'great': np.int64(847),
 'world': np.int64(2437),
 'la': np.int64(1098),
 'cine': np.int64(329),
 'get': np.int64(756),
 'wat': np.int64(2341),
 'ok': np.int64(1483),
 'lar': np.int64(1110),
 'wif': np.int64(2403),
 'free': np.int64(704),
 'entry': np.int64(602),
 'wkly': np.int64(2426),
 'comp': np.int64(387),
 'win': np.int64(2408),
 'cup': np.int64(452),
 'final': np.int64(669),
 'st': np.int64(1956),
 'may': np.int64(1263),
 'text': np.int64(2076),
 'receive': np.int64(1701),
 'question': np.int64(1667),
 'std': np.int64(1971),
 'txt': np.int64(2198),
 'rate': np.int64(1682),
 'apply': np.int64(77),
 'free entry': np.int64(709),
 'entry wkly': np.int64(604),
 'std txt': np.int64(1972),
 'txt rate': np.int64(2203),
 'rate apply': np.int64(1683),
 'dun': np.int64(561),
 'say': np.int64(1792),
 'early': np.int64(571),
 'already': np.int64(49),
 'nah': np.int64(1392),
 'think': np.int64(2096),
 'usf': np.int64(2263),
 'live': np.int64(1174),
 'around': np.int64(89),
 'though': np.int64(2108),
 'think go': np.int64(2099),
 'freemsg': np.int64(716),
 'hey': np.int64(918),
 'darling': np.int64(471),
 'week': np.int64(2369),
 'word': np.int64(2433),
 'back': np.int64(129),
 'like': np.int64(1160),
 'fun': np.int64(734),
 'still': np.int64(1975),
 'tb': np.int64(2056),
 'xxx': np.int64(2463),
 'send': np.int64(1825),
 'even': np.int64(612),
 'brother': np.int64(208),
 'speak': np.int64(1936),
 'treat': np.int64(2172),
 'per': np.int64(1544),
 'request': np.int64(1738),
 'melle': np.int64(1280),
 'set': np.int64(1845),
 'callertune': np.int64(262),
 'caller': np.int64(259),
 'press': np.int64(1636),
 'copy': np.int64(422),
 'friend': np.int64(722),
 'per request': np.int64(1548),
 'set callertune': np.int64(1846),
 'callertune caller': np.int64(263),
 'caller press': np.int64(260),
 'press copy': np.int64(1637),
 'copy friend': np.int64(423),
 'friend callertune': np.int64(723),
 'winner': np.int64(2413),
 'value': np.int64(2272),
 'network': np.int64(1411),
 'customer': np.int64(458),
 'select': np.int64(1818),
 'prize': np.int64(1648),
 'reward': np.int64(1750),
 'claim': np.int64(332),
 'call': np.int64(233),
 'code': np.int64(356),
 'valid': np.int64(2269),
 'hour': np.int64(967),
 'claim call': np.int64(333),
 'call claim': np.int64(237),
 'claim code': np.int64(334),
 'valid hour': np.int64(2270),
 'mobile': np.int64(1331),
 'month': np.int64(1351),
 'entitle': np.int64(600),
 'update': np.int64(2229),
 'late': np.int64(1117),
 'colour': np.int64(370),
 'camera': np.int64(266),
 'co': np.int64(353),
 'entitle update': np.int64(601),
 'update late': np.int64(2231),
 'late colour': np.int64(1119),
 'free call': np.int64(707),
 'call mobile': np.int64(247),
 'mobile update': np.int64(1340),
 'update co': np.int64(2230),
 'co free': np.int64(354),
 'gonna': np.int64(828),
 'home': np.int64(950),
 'soon': np.int64(1925),
 'want': np.int64(2326),
 'talk': np.int64(2052),
 'stuff': np.int64(2009),
 'anymore': np.int64(66),
 'tonight': np.int64(2155),
 'cry': np.int64(447),
 'enough': np.int64(597),
 'today': np.int64(2137),
 'want talk': np.int64(2337),
 'chance': np.int64(308),
 'cash': np.int64(290),
 'pound': np.int64(1623),
 'cost': np.int64(426),
 'day': np.int64(476),
 'reply': np.int64(1726),
 'hl': np.int64(933),
 'info': np.int64(1009),
 'chance win': np.int64(310),
 'win cash': np.int64(2409),
 'reply hl': np.int64(1730),
 'hl info': np.int64(934),
 'urgent': np.int64(2253),
 'membership': np.int64(1283),
 'www': np.int64(2451),
 'net': np.int64(1408),
 'pobox': np.int64(1606),
 'ldnw': np.int64(1134),
 'week free': np.int64(2372),
 'txt word': np.int64(2205),
 'search': np.int64(1805),
 'right': np.int64(1752),
 'thank': np.int64(2087),
 'promise': np.int64(1659),
 'wont': np.int64(2432),
 'take': np.int64(2048),
 'help': np.int64(916),
 'wonderful': np.int64(2431),
 'blessing': np.int64(179),
 'time': np.int64(2121),
 'date': np.int64(474),
 'sunday': np.int64(2026),
 'use': np.int64(2261),
 'credit': np.int64(442),
 'click': np.int64(346),
 'wap': np.int64(2338),
 'link': np.int64(1169),
 'next': np.int64(1426),
 'message': np.int64(1289),
 'http': np.int64(976),
 'com': np.int64(373),
 'oh': np.int64(1478),
 'eh': np.int64(581),
 'remember': np.int64(1719),
 'spell': np.int64(1947),
 'name': np.int64(1394),
 'yes': np.int64(2479),
 'naughty': np.int64(1399),
 'make': np.int64(1236),
 'wet': np.int64(2392),
 'fine': np.int64(677),
 'way': np.int64(2353),
 'feel': np.int64(658),
 'england': np.int64(593),
 'dont': np.int64(541),
 'miss': np.int64(1319),
 'goal': np.int64(824),
 'team': np.int64(2061),
 'news': np.int64(1425),
 'ur': np.int64(2232),
 'national': np.int64(1396),
 'eg': np.int64(579),
 'try': np.int64(2179),
 'wq': np.int64(2445),
 'dont miss': np.int64(543),
 'seriously': np.int64(1841),
 'ha': np.int64(882),
 'joke': np.int64(1056),
 'ha ha': np.int64(883),
 'pay': np.int64(1539),
 'first': np.int64(680),
 'da': np.int64(463),
 'stock': np.int64(1980),
 'comin': np.int64(385),
 'aft': np.int64(25),
 'finish': np.int64(679),
 'lunch': np.int64(1227),
 'str': np.int64(2002),
 'lor': np.int64(1197),
 'ard': np.int64(83),
 'smth': np.int64(1905),
 'alright': np.int64(50),
 'meet': np.int64(1274),
 'eat': np.int64(575),
 'really': np.int64(1696),
 'hungry': np.int64(981),
 'tho': np.int64(2107),
 'suck': np.int64(2019),
 'mark': np.int64(1248),
 'worry': np.int64(2438),
 'know': np.int64(1088),
 'sick': np.int64(1867),
 'turn': np.int64(2192),
 'pizza': np.int64(1572),
 'lol': np.int64(1187),
 'always': np.int64(53),
 'catch': np.int64(299),
 'bus': np.int64(219),
 'egg': np.int64(580),
 'tea': np.int64(2059),
 'mom': np.int64(1346),
 'leave': np.int64(1138),
 'dinner': np.int64(521),
 'love': np.int64(1202),
 'amp': np.int64(56),
 'pack': np.int64(1524),
 'car': np.int64(278),
 'let': np.int64(1147),
 'room': np.int64(1766),
 'let know': np.int64(1149),
 'work': np.int64(2434),
 'feel like': np.int64(659),
 'wait': np.int64(2309),
 'clear': np.int64(345),
 'sure': np.int64(2038),
 'yeah': np.int64(2473),
 'fall': np.int64(644),
 'child': np.int64(323),
 'till': np.int64(2120),
 'cheer': np.int64(320),
 'yeah get': np.int64(2474),
 'tell': np.int64(2065),
 'anything': np.int64(68),
 'tell anything': np.int64(2066),
 'quick': np.int64(1668),
 'thanks': np.int64(2088),
 'subscription': np.int64(2018),
 'ringtone': np.int64(1755),
 'uk': np.int64(2213),
 'charge': np.int64(313),
 'please': np.int64(1582),
 'confirm': np.int64(399),
 'mobile charge': np.int64(1333),
 'reply yes': np.int64(1733),
 'yup': np.int64(2497),
 'look': np.int64(1193),
 'timing': np.int64(2128),
 'msg': np.int64(1371),
 'learn': np.int64(1136),
 'nd': np.int64(1400),
 'lesson': np.int64(1146),
 'ok go': np.int64(1485),
 'go home': np.int64(812),
 'oops': np.int64(1502),
 'roommate': np.int64(1767),
 'do': np.int64(534),
 'see': np.int64(1813),
 'letter': np.int64(1150),
 'decide': np.int64(495),
 'anything lor': np.int64(69),
 'hello': np.int64(915),
 'saturday': np.int64(1786),
 'texting': np.int64(2084),
 'tomo': np.int64(2147),
 'invite': np.int64(1019),
 'pls': np.int64(1588),
 'ahead': np.int64(33),
 'weekend': np.int64(2377),
 'abiola': np.int64(1),
 'great weekend': np.int64(850),
 'forget': np.int64(696),
 'need': np.int64(1404),
 'crave': np.int64(439),
 'sweet': np.int64(2042),
 'want need': np.int64(2331),
 'burn': np.int64(218),
 'sm': np.int64(1896),
 'nokia': np.int64(1440),
 'camcorder': np.int64(264),
 'delivery': np.int64(505),
 'tomorrow': np.int64(2148),
 'call reply': np.int64(252),
 'nokia mobile': np.int64(1444),
 'mobile free': np.int64(1336),
 'free camcorder': np.int64(708),
 'please call': np.int64(1583),
 'delivery tomorrow': np.int64(506),
 'hope': np.int64(955),
 'man': np.int64(1241),
 'well': np.int64(2386),
 'lt': np.int64(1218),
 'gt': np.int64(858),
 'inch': np.int64(1004),
 'lt gt': np.int64(1220),
 'miss call': np.int64(1322),
 'nigeria': np.int64(1431),
 'hopefully': np.int64(959),
 'tyler': np.int64(2210),
 'could': np.int64(431),
 'maybe': np.int64(1266),
 'ask': np.int64(98),
 'bit': np.int64(174),
 'hospital': np.int64(962),
 'keep': np.int64(1070),
 'weak': np.int64(2362),
 'want go': np.int64(2329),
 'saw': np.int64(1791),
 'class': np.int64(342),
 'first time': np.int64(681),
 'usually': np.int64(2265),
 'run': np.int64(1773),
 'half': np.int64(888),
 'smart': np.int64(1899),
 'almost': np.int64(46),
 'whole': np.int64(2400),
 'second': np.int64(1808),
 'like lt': np.int64(1163),
 'fyi': np.int64(737),
 'ride': np.int64(1751),
 'morning': np.int64(1356),
 'place': np.int64(1573),
 'wow': np.int64(2444),
 'never': np.int64(1416),
 'realize': np.int64(1695),
 'since': np.int64(1876),
 'best': np.int64(164),
 'seem': np.int64(1817),
 'happy': np.int64(896),
 'sorry': np.int64(1926),
 'give': np.int64(796),
 'offer': np.int64(1473),
 'ac': np.int64(4),
 'new': np.int64(1417),
 'red': np.int64(1706),
 'play': np.int64(1576),
 'ice': np.int64(988),
 'correct': np.int64(424),
 'end': np.int64(588),
 'sm ac': np.int64(1897),
 'yesterday': np.int64(2485),
 'find': np.int64(672),
 'congrats': np.int64(400),
 'year': np.int64(2476),
 'special': np.int64(1939),
 'cinema': np.int64(330),
 'pas': np.int64(1535),
 'etc': np.int64(608),
 'bx': np.int64(224),
 'ip': np.int64(1023),
 'pm': np.int64(1600),
 'etc free': np.int64(609),
 'bx ip': np.int64(225),
 'ip pm': np.int64(1024),
 'later': np.int64(1122),
 'meeting': np.int64(1277),
 'sorry call': np.int64(1927),
 'call later': np.int64(245),
 'later meeting': np.int64(1123),
 'reach': np.int64(1689),
 'pick': np.int64(1562),
 'move': np.int64(1363),
 'pain': np.int64(1526),
 'kill': np.int64(1082),
 'way home': np.int64(2356),
 'good': np.int64(830),
 'girl': np.int64(793),
 'situation': np.int64(1886),
 'part': np.int64(1531),
 'check': np.int64(319),
 'iq': np.int64(1027),
 'forever': np.int64(695),
 'come': np.int64(376),
 'ok come': np.int64(1484),
 'double': np.int64(546),
 'hair': np.int64(887),
 'wun': np.int64(2450),
 'cut': np.int64(460),
 'short': np.int64(1860),
 'nice': np.int64(1429),
 'follow': np.int64(690),
 'review': np.int64(1749),
 'mob': np.int64(1329),
 'award': np.int64(117),
 'bonus': np.int64(185),
 'award bonus': np.int64(118),
 'prize call': np.int64(1649),
 'song': np.int64(1921),
 'frnds': np.int64(729),
 'rply': np.int64(1771),
 'send ur': np.int64(1837),
 'complimentary': np.int64(392),
 'trip': np.int64(2173),
 'dis': np.int64(526),
 'ur award': np.int64(2233),
 'hear': np.int64(909),
 'plane': np.int64(1575),
 'wah': np.int64(2308),
 'lucky': np.int64(1225),
 'save': np.int64(1790),
 'money': np.int64(1350),
 'hee': np.int64(912),
 'hi': np.int64(922),
 'babe': np.int64(125),
 'im': np.int64(996),
 'wanna': np.int64(2325),
 'something': np.int64(1917),
 'xx': np.int64(2462),
 'hi babe': np.int64(923),
 'call free': np.int64(239),
 'thats': np.int64(2091),
 'cool': np.int64(420),
 'respect': np.int64(1740),
 'thats cool': np.int64(2092),
 'people': np.int64(1543),
 'much': np.int64(1381),
 'pa': np.int64(1522),
 'job': np.int64(1051),
 'ta': np.int64(2047),
 'ah': np.int64(31),
 'hi hi': np.int64(925),
 'stop': np.int64(1984),
 'urgnt': np.int64(2259),
 'real': np.int64(1694),
 'yo': np.int64(2489),
 'ticket': np.int64(2118),
 'one': np.int64(1497),
 'start': np.int64(1964),
 'bed': np.int64(156),
 'coin': np.int64(361),
 'gotta': np.int64(844),
 'come back': np.int64(377),
 'kano': np.int64(1067),
 'il': np.int64(994),
 'download': np.int64(548),
 'wen': np.int64(2389),
 'wen ur': np.int64(2390),
 'stand': np.int64(1960),
 'close': np.int64(348),
 'another': np.int64(62),
 'night': np.int64(1432),
 'spend': np.int64(1948),
 'afternoon': np.int64(26),
 'mean': np.int64(1268),
 'moro': np.int64(1359),
 'include': np.int64(1005),
 'smile': np.int64(1900),
 'pleasure': np.int64(1586),
 'trouble': np.int64(2174),
 'rain': np.int64(1678),
 'sum': np.int64(2023),
 'hurt': np.int64(984),
 'someone': np.int64(1914),
 'service': np.int64(1842),
 'representative': np.int64(1735),
 'guaranteed': np.int64(870),
 'call customer': np.int64(238),
 'customer service': np.int64(459),
 'service representative': np.int64(1844),
 'representative pm': np.int64(1737),
 'pm guaranteed': np.int64(1602),
 'guaranteed cash': np.int64(872),
 'cash prize': np.int64(296),
 'havent': np.int64(907),
 'buy': np.int64(222),
 'show': np.int64(1861),
 'collect': np.int64(365),
 'simply': np.int64(1875),
 'password': np.int64(1537),
 'verify': np.int64(2274),
 'po': np.int64(1604),
 'box': np.int64(197),
 'free ringtone': np.int64(713),
 'po box': np.int64(1605),
 'watch': np.int64(2346),
 'movie': np.int64(1364),
 'abt': np.int64(3),
 'wat abt': np.int64(2342),
 'load': np.int64(1178),
 'loan': np.int64(1179),
 'wk': np.int64(2424),
 'appointment': np.int64(78),
 'shower': np.int64(1864),
 'cause': np.int64(300),
 'prob': np.int64(1654),
 'need get': np.int64(1405),
 'get home': np.int64(766),
 'coffee': np.int64(360),
 'nothing': np.int64(1457),
 'else': np.int64(583),
 'okay': np.int64(1492),
 'price': np.int64(1639),
 'long': np.int64(1190),
 'ave': np.int64(113),
 'drive': np.int64(555),
 'test': np.int64(2075),
 'yet': np.int64(2486),
 'guess': np.int64(878),
 'boston': np.int64(193),
 'men': np.int64(1284),
 'change': np.int64(311),
 'location': np.int64(1181),
 'cuz': np.int64(462),
 'page': np.int64(1525),
 'umma': np.int64(2215),
 'life': np.int64(1155),
 'lot': np.int64(1200),
 'dear': np.int64(491),
 'love lot': np.int64(1207),
 'wish': np.int64(2415),
 'birthday': np.int64(172),
 'truly': np.int64(2176),
 'aight': np.int64(35),
 'hit': np.int64(931),
 'get cash': np.int64(760),
 'would': np.int64(2442),
 'address': np.int64(17),
 'consider': np.int64(406),
 'computer': np.int64(393),
 'old': np.int64(1494),
 'lie': np.int64(1154),
 'busy': np.int64(221),
 'research': np.int64(1739),
 'go dinner': np.int64(810),
 'cos': np.int64(425),
 'thing': np.int64(2095),
 'scar': np.int64(1799),
 'mah': np.int64(1232),
 'contact': np.int64(407),
 'last': np.int64(1112),
 'draw': np.int64(549),
 'hr': np.int64(974),
 'ppm': np.int64(1628),
 'try contact': np.int64(2180),
 'contact last': np.int64(412),
 'last weekend': np.int64(1116),
 'weekend draw': np.int64(2379),
 'draw show': np.int64(551),
 'show prize': np.int64(1862),
 'prize guaranteed': np.int64(1652),
 'guaranteed call': np.int64(871),
 'code valid': np.int64(359),
 'valid hr': np.int64(2271),
 'hr ppm': np.int64(975),
 'wa': np.int64(2307),
 'anyway': np.int64(72),
 'juz': np.int64(1065),
 'tt': np.int64(2188),
 'eatin': np.int64(576),
 'weight': np.int64(2383),
 'haha': np.int64(885),
 'happen': np.int64(894),
 'enter': np.int64(598),
 'cabin': np.int64(227),
 'bos': np.int64(191),
 'felt': np.int64(661),
 'askd': np.int64(99),
 'apartment': np.int64(73),
 'enter cabin': np.int64(599),
 'cabin pa': np.int64(228),
 'pa say': np.int64(1523),
 'say happy': np.int64(1794),
 'happy day': np.int64(898),
 'day bos': np.int64(478),
 'bos felt': np.int64(192),
 'felt special': np.int64(662),
 'special askd': np.int64(1940),
 'askd lunch': np.int64(100),
 'lunch lunch': np.int64(1229),
 'lunch invite': np.int64(1228),
 'invite apartment': np.int64(1020),
 'apartment go': np.int64(74),
 'specially': np.int64(1944),
 'holiday': np.int64(944),
 'flight': np.int64(686),
 'inc': np.int64(1003),
 'operator': np.int64(1504),
 'min': np.int64(1300),
 'winner specially': np.int64(2414),
 'specially select': np.int64(1945),
 'select receive': np.int64(1819),
 'holiday flight': np.int64(947),
 'speak live': np.int64(1937),
 'live operator': np.int64(1176),
 'operator claim': np.int64(1505),
 'must': np.int64(1389),
 'friday': np.int64(721),
 'hmm': np.int64(936),
 'uncle': np.int64(2219),
 'inform': np.int64(1010),
 'school': np.int64(1801),
 'directly': np.int64(524),
 'food': np.int64(692),
 'private': np.int64(1646),
 'account': np.int64(8),
 'statement': np.int64(1967),
 'identifier': np.int64(991),
 'expire': np.int64(635),
 'private account': np.int64(1647),
 'account statement': np.int64(9),
 'statement show': np.int64(1968),
 'call identifier': np.int64(241),
 'identifier code': np.int64(992),
 'landline': np.int64(1105),
 'urgent mobile': np.int64(2256),
 'mobile award': np.int64(1332),
 'bonus caller': np.int64(186),
 'caller prize': np.int64(261),
 'contact call': np.int64(408),
 'call landline': np.int64(244),
 'voda': np.int64(2294),
 'number': np.int64(1464),
 'match': np.int64(1251),
 'quote': np.int64(1673),
 'standard': np.int64(1961),
 'app': np.int64(75),
 'today voda': np.int64(2145),
 'voda number': np.int64(2295),
 'number end': np.int64(1466),
 'end select': np.int64(589),
 'receive award': np.int64(1702),
 'match please': np.int64(1252),
 'call quote': np.int64(251),
 'quote claim': np.int64(1674),
 'code standard': np.int64(358),
 'standard rate': np.int64(1962),
 'mu': np.int64(1380),
 'wat time': np.int64(2344),
 'time finish': np.int64(2123),
 'bother': np.int64(194),
 'send text': np.int64(1836),
 'del': np.int64(501),
 'bak': np.int64(134),
 'long time': np.int64(1191),
 'give call': np.int64(798),
 'dear call': np.int64(492),
 'answer': np.int64(64),
 'sunshine': np.int64(2030),
 'quiz': np.int64(1671),
 'top': np.int64(2157),
 'sony': np.int64(1922),
 'dvd': np.int64(568),
 'player': np.int64(1579),
 'country': np.int64(432),
 'sp': np.int64(1934),
 'sunshine quiz': np.int64(2031),
 'quiz wkly': np.int64(1672),
 'sony dvd': np.int64(1923),
 'dvd player': np.int64(569),
 'player know': np.int64(1580),
 'know country': np.int64(1090),
 'txt ansr': np.int64(2199),
 'lay': np.int64(1129),
 'direct': np.int64(523),
 'join': np.int64(1054),
 'large': np.int64(1111),
 'dog': np.int64(538),
 'bt': np.int64(210),
 'txting': np.int64(2207),
 'nt': np.int64(1459),
 'ec': np.int64(577),
 'want get': np.int64(2328),
 'get lay': np.int64(769),
 'want real': np.int64(2333),
 'send direct': np.int64(1827),
 'ur mob': np.int64(2244),
 'join uk': np.int64(1055),
 'haf': np.int64(884),
 'yijue': np.int64(2487),
 'chat': np.int64(317),
 'age': np.int64(29),
 'yr': np.int64(2493),
 'go get': np.int64(811),
 'lazy': np.int64(1130),
 'type': np.int64(2211),
 'lect': np.int64(1140),
 'sir': np.int64(1881),
 'mail': np.int64(1234),
 'sir wait': np.int64(1882),
 'swt': np.int64(2045),
 'tire': np.int64(2129),
 'little': np.int64(1173),
 'lovable': np.int64(1201),
 'person': np.int64(1550),
 'coz': np.int64(436),
 'big': np.int64(168),
 'heart': np.int64(910),
 'gud': np.int64(873),
 'ni': np.int64(1428),
 'gud ni': np.int64(876),
 'open': np.int64(1503),
 'ya': np.int64(2466),
 'yes see': np.int64(2483),
 'whats': np.int64(2395),
 'sexy': np.int64(1849),
 'local': np.int64(1180),
 'luv': np.int64(1230),
 'netcollex': np.int64(1410),
 'ltd': np.int64(1222),
 'per msg': np.int64(1547),
 'reply stop': np.int64(1732),
 'stop end': np.int64(1987),
 'begin': np.int64(160),
 'qatar': np.int64(1665),
 'pray': np.int64(1633),
 'hard': np.int64(902),
 'delete': np.int64(503),
 'get job': np.int64(767),
 'wine': np.int64(2412),
 'thk': np.int64(2105),
 'yup thk': np.int64(2498),
 'need go': np.int64(1406),
 'shirt': np.int64(1855),
 'sometimes': np.int64(1919),
 'dream': np.int64(553),
 'without': np.int64(2422),
 'joy': np.int64(1059),
 'tv': np.int64(2193),
 'become': np.int64(155),
 'house': np.int64(968),
 'leave house': np.int64(1139),
 'interview': np.int64(1017),
 'boy': np.int64(200),
 'arrange': np.int64(91),
 'new year': np.int64(1424),
 'receive cash': np.int64(1703),
 'cash holiday': np.int64(295),
 'safe': np.int64(1780),
 'everyone': np.int64(620),
 'miss already': np.int64(1320),
 'parent': np.int64(1528),
 'hand': np.int64(891),
 'new job': np.int64(1418),
 'sms': np.int64(1903),
 'frnd': np.int64(728),
 'invite friend': np.int64(1021),
 'friend reply': np.int64(724),
 'see www': np.int64(1816),
 'www sms': np.int64(2455),
 'sms ac': np.int64(1904),

In [80]:
## Predictions
y_pred = model.predict(X_test)

In [81]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, y_pred)
print(score)

0.9668161434977578

In [82]:
from sklearn.metrics import classification_report
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98      1003
           1       0.75      1.00      0.86       112

    accuracy                           0.97      1115
   macro avg       0.88      0.98      0.92      1115
weighted avg       0.98      0.97      0.97      1115

## creating the model Using BOW

In [36]:
messages.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [37]:
# output feature
y = pd.get_dummies(messages['label'])

In [38]:
y

        ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]